{
 "title": "Acknowledgements",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(daml_sequencer_client_handler_delay,namespace)"
    }
   },
   {
    "name": "migration",
    "query": {
     "query": "label_values(daml_sequencer_client_handler_delay{namespace=~\"$namespace\"},job)"
    }
   },
   {
    "name": "member",
    "query": {
     "query": "label_values(daml_sequencer_block_acknowledgments_micros,member)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Client Delay", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "Canton", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Most recent acknowledgement",
   "type": "timeseries",
   "description": "The most recent acknowledgement the sequencer has seen from that member. Acknowledgements are only sent when the member also receives an event addressed to them so a node that never receives anything can lag behind. Sequencers only receive topology transactions which are rare so we filter them out.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "targets": [
    {
     "expr": "daml_sequencer_block_acknowledgments_micros{namespace=~\"$namespace\", job=~\"global-domain-$migration-sequencer\",member!~\"SEQ::.*\",member=~\"$member\"} / 1000",
     "legendFormat": "{{namespace}} M$migration {{member}}"
    }
   ]
  },
  {
   "title": "Acknowledgement lag",
   "type": "timeseries",
   "description": "The difference most recent acknowledgement the sequencer has seen from that member and the maximum across all members. Acknowledgements are only sent when the member also receives an event addressed to them so a node that never receives anything can lag behind. Sequencers only receive topology transactions which are rare so we filter them out.",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(max without (member) (daml_sequencer_block_acknowledgments_micros{namespace=~\"$namespace\", job=~\"global-domain-$migration-sequencer\"}) - ignoring (member) group_right daml_sequencer_block_acknowledgments_micros{namespace=~\"$namespace\", job=~\"global-domain-$migration-sequencer\",member!~\"SEQ::.*\",member=~\"$member\"}) / 1000000",
     "legendFormat": "{{namespace}} M$migration {{member}}"
    }
   ]
  },
  {
   "title": "Acknowledgement catchup speed",
   "type": "timeseries",
   "description": "The increase in acknowledgement time in acknowledgements over the last 10min for a given member. This should usually be around 1. If a node was down, they should show > 1. If the value is < 1 the node might never catch up. Acknowledgements are only sent when the member also receives an event addressed to them so a node that never receives anything can lag behind. Sequencers only receive topology transactions which are rare so we filter them out.",
   "gridPos": { "h": 10, "w": 13, "x": 11, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "delta(daml_sequencer_block_acknowledgments_micros{namespace=~\"$namespace\", job=~\"global-domain-$migration-sequencer\",member!~\"SEQ::.*\",member=~\"$member\"}[10m]) / (1000000 * 60 * 10)",
     "legendFormat": "{{namespace}} M$migration {{member}}"
    }
   ]
  },
  { "title": "CometBFT", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } }
 ]
}