{
 "title": "ACS Commitment Performance PV >= 36",
 "description": "ACS Commitment Performance for the new commitments introduced in Canton 3.6. They are active as soon as you upgrade in parallel to the old one but only sent and received once a synchronizer upgrades to PV >= 36.",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(daml_participant_sync_commitments_digest_processor_health,namespace)"
    }
   },
   {
    "name": "job",
    "query": {
     "query": "label_values(daml_participant_sync_commitments_digest_processor_health,job)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Digest Processor Health",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "max by (namespace, job) (daml_participant_sync_commitments_digest_processor_health{namespace=~\"$namespace\", job=~\"$job\"})",
     "legendFormat": "{{namespace}}-{{job}}"
    }
   ]
  },
  {
   "title": "Matcher Health",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "max by (namespace, job) (daml_participant_sync_commitments_matcher_health{namespace=~\"$namespace\", job=~\"$job\"})",
     "legendFormat": "{{namespace}}-{{job}}"
    }
   ]
  },
  {
   "title": "Tick Signaller Health",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "max by (namespace, job) (daml_participant_sync_commitments_tick_signaller_health{namespace=~\"$namespace\", job=~\"$job\"})",
     "legendFormat": "{{namespace}}-{{job}}"
    }
   ]
  },
  { "title": "Catchup", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Commitment Checkpoint Lag",
   "type": "timeseries",
   "description": "Lag behind the timestamp the commitment checkpoint was created and the timestamp of the checkpoint; periodic lag spikes during commitment computation are expected",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "min by (namespace, job) ((timestamp(daml_participant_sync_commitments_checkpoint_watermark{namespace=~\"$namespace\",job=~\"$job\"}) - ((daml_participant_sync_commitments_checkpoint_watermark{namespace=~\"$namespace\",job=~\"$job\"} > 0) / 1e6)))",
     "legendFormat": "{{namespace}}-{{job}}"
    }
   ]
  },
  {
   "title": " Completed ACS Commitment Lag",
   "type": "timeseries",
   "description": "Lag behind the timestamp of when the last completed commitment interval was processed and the timestamp of the interval",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "min by (namespace, job) (timestamp(daml_participant_sync_commitments_tick_watermark{namespace=~\"$namespace\",job=~\"$job\"}) - ((daml_participant_sync_commitments_tick_watermark{namespace=~\"$namespace\",job=~\"$job\"} > 0) / 1e6))",
     "legendFormat": "{{namespace}}-{{job}}"
    }
   ]
  },
  {
   "title": " Incoming Received ACS Commitment Lag",
   "type": "timeseries",
   "description": "Lag behind the timestamp the commitment was received and the timestamp of the commitment",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "min by (namespace, job) (timestamp(daml_participant_sync_commitments_received_watermark{namespace=~\"$namespace\",job=~\"$job\"}) - ((daml_participant_sync_commitments_received_watermark{namespace=~\"$namespace\",job=~\"$job\"} > 0) / 1e6))",
     "legendFormat": "{{namespace}}-{{job}}"
    }
   ]
  },
  {
   "title": " Incoming Processed ACS Commitment Lag",
   "type": "timeseries",
   "description": "Lag behind the timestamp the commitment was processed and the timestamp of the commitment",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "min by (namespace, job) (timestamp(daml_participant_sync_commitments_matching_watermark{namespace=~\"$namespace\",job=~\"$job\"}) - ((daml_participant_sync_commitments_matching_watermark{namespace=~\"$namespace\",job=~\"$job\"} > 0) / 1e6))",
     "legendFormat": "{{namespace}}-{{job}}"
    }
   ]
  },
  {
   "title": "ACS Commitment Sender Lag",
   "type": "timeseries",
   "description": "Lag behind wallclock time and the time of the commitment the sender was processing",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "min by (namespace, job) (timestamp(daml_participant_sync_commitments_sender_watermark_timestamp{namespace=~\"$namespace\",job=~\"$job\"}) - ((daml_participant_sync_commitments_sender_watermark_timestamp{namespace=~\"$namespace\",job=~\"$job\"} > 0) / 1e6))",
     "legendFormat": "{{namespace}}-{{job}}"
    }
   ]
  },
  {
   "title": "Last Locally Completed ACS Commitment",
   "type": "timeseries",
   "description": "Timestamp of the latest locally completed ACS commitment interval. Crash recovery will start reingesting from this timestamp on or from the latest checkpointed ACS commitment interval on, whichever is later.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "targets": [
    {
     "expr": "max by (namespace, job)(daml_participant_sync_commitments_tick_watermark{namespace=~\"$namespace\", job=~\"$job\"} > 0)/1e3",
     "legendFormat": "{{namespace}}-{{job}}"
    }
   ]
  },
  {
   "title": "Last Locally Checkpointed ACS Commitment",
   "type": "timeseries",
   "description": "Timestamp of the latest checkpointed ACS commitment in microseconds. Crash recovery will start reingesting from this timestamp on or from the latest locally completed ACS commitment interval on, whichever is later.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "targets": [
    {
     "expr": "max by (namespace, job)(daml_participant_sync_commitments_checkpoint_watermark{namespace=~\"$namespace\", job=~\"$job\"} > 0)/1e3",
     "legendFormat": "{{namespace}}-{{job}}"
    }
   ]
  },
  {
   "title": "Last Incoming Processed ACS Commitment",
   "type": "timeseries",
   "description": "Timestamp of the latest incoming ACS commitment period end that was fully processed by the participant.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "targets": [
    {
     "expr": "max by (namespace, job)(daml_participant_sync_commitments_matching_watermark{namespace=~\"$namespace\", job=~\"$job\"} > 0)/1e3",
     "legendFormat": "{{namespace}}-{{job}}"
    }
   ]
  },
  {
   "title": "Last Incoming Received ACS Commitment",
   "type": "timeseries",
   "description": "Timestamp of the latest incoming ACS commitment period end that has been received and enqueued, but not yet processed by the participant.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "targets": [
    {
     "expr": "max by (namespace, job)(daml_participant_sync_commitments_received_watermark{namespace=~\"$namespace\", job=~\"$job\"} != -62135596800000000)/1e3",
     "legendFormat": "{{namespace}}-{{job}}"
    }
   ]
  },
  {
   "title": "Last Sent ACS Commitment",
   "type": "timeseries",
   "description": "Timestamp of the latest sent ACS commitment",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "targets": [
    {
     "expr": "max by (namespace, job)(daml_participant_sync_commitments_sender_watermark_timestamp{namespace=~\"$namespace\", job=~\"$job\"} != -62135596800000000)/1e3",
     "legendFormat": "{{namespace}}-{{job}}"
    }
   ]
  },
  { "title": "Initialization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 } },
  {
   "title": "Contract Changes",
   "type": "timeseries",
   "description": "This metric measures the progress in the number of identified contract changes upon reinitializing the digests. This metric is reset to 0 at the start of reinitialization. Since the same contract may be processed multiple times (for different counterparties), this metric may exceed the number of active contracts.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "max by (namespace, job) (daml_participant_sync_commitments_reinitialize_contract_changes{namespace=~\"$namespace\",job=~\"$job\"})",
     "legendFormat": "{{namespace}}-{{job}}"
    }
   ]
  },
  {
   "title": "Parties",
   "type": "timeseries",
   "description": "This metric measures progress in the number of counterparties during the digest processor reinitialization. This metric is reset to 0 at the start of reinitialization.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "targets": [
    {
     "expr": "max by (namespace, job) (daml_participant_sync_commitments_reinitialize_parties{namespace=~\"$namespace\",job=~\"$job\"})",
     "legendFormat": "{{namespace}}-{{job}}"
    }
   ]
  },
  {
   "title": "Tombstones",
   "type": "timeseries",
   "description": "This metric measures progress in the number of persisted tombstones during the digest processor reinitialization. This metric is reset to 0 at the start of reinitialization.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "targets": [
    {
     "expr": "max by (namespace, job) (daml_participant_sync_commitments_reinitialize_tombstones{namespace=~\"$namespace\",job=~\"$job\"})",
     "legendFormat": "{{namespace}}-{{job}}"
    }
   ]
  }
 ]
}