{
 "title": "Logical Synchronizer Upgrade",
 "description": "LSU Sequencing Tests between Topology Freeze and Upgrade Time",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(daml_participant_lsu_status,namespace)"
    }
   },
   {
    "name": "job",
    "query": {
     "query": "label_values(daml_sequencer_public_api_handshakes_total{namespace=\"$namespace\"},job)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Report Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "LSU Sequencing Test Mesages Received in the last 5m",
   "type": "gauge",
   "description": "LSU Sequencing Test Messages Received in the last 5m by sender",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (sender) (increase(daml_received_lsu_sequencing_test_messages_total{namespace=\"$namespace\"}[5m]))",
     "legendFormat": "{{sender}}"
    }
   ]
  },
  {
   "title": "LSU Sequencing Test Rate by Sender",
   "type": "timeseries",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by (sender) (rate(daml_received_lsu_sequencing_test_messages_total{namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "{{sender}}"
    }
   ]
  },
  { "title": "Handshakes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Unique Members Handshaking",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(max by (namespace, job, member)(daml_sequencer_public_api_handshakes_total{namespace=\"$namespace\", job=~\"$job\"}) > 0)",
     "legendFormat": "Unique Members"
    }
   ]
  },
  {
   "title": "Handshakes per Member",
   "type": "table",
   "gridPos": { "h": 9, "w": 18, "x": 6, "y": 30 },
   "targets": [
    {
     "expr": "sum by (member) (increase(daml_sequencer_public_api_handshakes_total{namespace=\"$namespace\", job=~\"$job\"}[$__range]))",
     "legendFormat": "{{member}}"
    }
   ]
  },
  { "title": "LSU State", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Participant LSU Status",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "daml_participant_lsu_status{namespace=\"$namespace\"}",
     "legendFormat": "{{job}} {{node}}"
    }
   ]
  }
 ]
}