{
 "title": "Participant",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(daml_participant_api_commands_max_in_flight_length,namespace)"
    }
   },
   {
    "name": "job",
    "query": {
     "query": "label_values(daml_participant_api_commands_max_in_flight_length{namespace=~\"$namespace\"},job)"
    }
   },
   {
    "name": "participant",
    "query": {
     "query": "label_values(daml_participant_api_commands_max_in_flight_length{namespace=~\"$namespace\", job=~\"$job\"},node)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Commands", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "In Flight Commands",
   "type": "timeseries",
   "description": "Daml commands through the synchronous CommandService currently in flight",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "submissions" } },
   "targets": [
    {
     "expr": "daml_participant_api_commands_max_in_flight_length{namespace=~\"$namespace\",component=\"participant\",job=~\"$job\", node=~\"$participant\"}",
     "legendFormat": "{{namespace}} {{job}} {{node}}"
    }
   ]
  },
  {
   "title": "Validation Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true
  },
  {
   "title": "Number of requests being validated",
   "type": "timeseries",
   "description": "Number of requests that are currently being validated. This also covers requests submitted by other participants.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "daml_participant_inflight_validation_requests{namespace=~\"$namespace\",job=~\"$job\",node=~\"$participant\"}",
     "legendFormat": "actual {{namespace}} {{job}} {{node}}"
    },
    {
     "expr": "daml_participant_max_inflight_validation_requests{namespace=~\"$namespace\",job=~\"$job\",node=~\"$participant\"}",
     "legendFormat": "max {{namespace}} {{job}} {{node}}"
    }
   ]
  },
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Health Status",
   "type": "state-timeline",
   "description": "Status of the participant (healthy or not)",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "Alive" } },
   "targets": [
    {
     "expr": "daml_health_status{namespace=~\"$namespace\",job=~\"$job\", node=~\"$participant\"}",
     "legendFormat": "{{namespace}} {{job}} {{node}} {{component}}"
    }
   ]
  }
 ]
}