{
 "title": "Sequencer Topology Transactions",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(daml_sequencer_block_events_total,namespace)"
    }
   },
   {
    "name": "job",
    "query": {
     "query": "label_values(daml_sequencer_block_events_total{namespace=\"$namespace\"},job)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Topology", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Topology send rate",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 16, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by(type) (rate(daml_sequencer_block_events_total{namespace=\"$namespace\", job=\"$job\", type=~\"send-topology|send-time-proof\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(daml_sequencer_block_events_total{namespace=\"$namespace\", job=\"$job\", type=~\"send-topology|send-time-proof\"}[1h]))",
     "legendFormat": "hourly total"
    }
   ]
  },
  {
   "title": "Topology transactions participants last 24h",
   "type": "table",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "sort_desc(sum by(member) (delta(daml_sequencer_block_events_total{namespace=\"$namespace\", job=\"$job\", type=\"send-topology\", member=~\"PAR::.*\"}[24h])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sequencer Topology Rate by Participant",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 16, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum by(member) (rate(daml_sequencer_block_events_total{namespace=\"$namespace\", job=\"$job\", member=~\"PAR::.*\", type=\"send-topology\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Topology transactions non participants last 24h",
   "type": "table",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 13 },
   "targets": [
    {
     "expr": "sort_desc(sum by(member) (delta(daml_sequencer_block_events_total{namespace=\"$namespace\", job=\"$job\", type=\"send-topology\", member!~\"PAR::.*\"}[24h])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sequencer Topology Rate by Non Participant",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum by(member) (rate(daml_sequencer_block_events_total{namespace=\"$namespace\", job=\"$job\", member!~\"PAR::.*\", type=\"send-topology\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Time Proofs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Time Proofs",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 16, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "sum by(member) (rate(daml_sequencer_block_events_total{namespace=\"$namespace\", job=\"$job\", type=\"send-time-proof\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Time Proofs last 24h",
   "type": "table",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 37 },
   "targets": [
    {
     "expr": "sort_desc(sum by(member) (delta(daml_sequencer_block_events_total{namespace=\"$namespace\", job=\"$job\", type=\"send-time-proof\"}[24h])))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Bytes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Topology send rate",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(type) (rate(daml_sequencer_block_event_bytes_total{namespace=\"$namespace\", job=\"$job\", type=~\"send-topology|send-time-proof\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(daml_sequencer_block_event_bytes_total{namespace=\"$namespace\", job=\"$job\", type=~\"send-topology|send-time-proof\"}[1h]))",
     "legendFormat": "hourly total"
    }
   ]
  },
  {
   "title": "Sequencer Topology Rate by Non Participant",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(member) (rate(daml_sequencer_block_event_bytes_total{namespace=\"$namespace\", job=\"$job\", type=~\"send-topology|send-time-proof\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}