{
 "title": "Sequencer Client",
 "description": "Metrics exposed by the sequencer client (aka sequencer connection) in participants and mediators",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(daml_sequencer_client_submissions_sequencing_duration_seconds,namespace)"
    }
   },
   {
    "name": "job",
    "query": {
     "query": "label_values(daml_sequencer_client_submissions_sequencing_duration_seconds{namespace=~\"$namespace\"},job)"
    }
   },
   {
    "name": "node",
    "query": {
     "query": "label_values(daml_sequencer_client_submissions_sequencing_duration_seconds{namespace=~\"$namespace\", job=~\"$job\"},node)"
    }
   },
   { "name": "quantile", "query": "0.9,0.95,0.99" }
  ]
 },
 "panels": [
  {
   "title": "Sequencer Submission Latency",
   "type": "timeseries",
   "description": "Latency of a sequencer submission from submission until the node observes it being sequenced.\nNote that this is the latency of an individuals sequencer submission not a Daml transaction which involves multiple sequencer submissions",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": " histogram_quantile($quantile, sum by (namespace, job, node) (rate(daml_sequencer_client_submissions_sequencing_duration_seconds{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\"}[$__rate_interval])))",
     "legendFormat": " ({{namespace}}, {{job}}) {{node}}"
    }
   ]
  },
  {
   "title": "Rate of sequencer submissions",
   "type": "timeseries",
   "description": "Rate of sequencer submissions both successful and failed",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "histogram_count(rate(daml_sequencer_client_submissions_sends_duration_seconds{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "{{namespace}} {{job}} {{node}} {{sequencer}}"
    }
   ]
  },
  {
   "title": "Rate of dropped sequencer submissions",
   "type": "timeseries",
   "description": "Rate of sequencer submissions that have not been sequenced.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum by (namespace, job, node) (rate(daml_sequencer_client_submissions_dropped{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "{{namespace}} {{job}} {{node}} {{sequencer}}"
    }
   ]
  },
  {
   "title": "Rate of received sequencer events",
   "type": "timeseries",
   "description": "Rate of events received from the sequencer",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "rate(daml_sequencer_client_handler_sequencer_events{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\"}[$__rate_interval])",
     "legendFormat": "{{namespace}} {{job}} {{node}} {{sequencer}}"
    }
   ]
  },
  {
   "title": "Sequencer Delay",
   "type": "timeseries",
   "description": "The sequencer delay on the overall BFT connection, i.e., the difference between wallclock time and record time of the last received event where an event only counts as received once it has been received from a threshold of SVs.\n\nNote that this only changes when a new event is received so if no events are received it will not go up.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "daml_sequencer_client_handler_delay{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\"}",
     "legendFormat": "{{namespace}} {{job}} {{node}}"
    }
   ]
  },
  {
   "title": "Delay per sequencer connection",
   "type": "timeseries",
   "description": "Delay between wallclock time and the record time of the last sequencer event received on each connection. Note that this only goes up or down if an event actually was received. So for a sequencer that is completely down you will not see it go up.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "daml_sequencer_client_handler_delay_per_connection{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\"}",
     "legendFormat": "{{namespace}} {{job}} {{node}} {{sequencer}}"
    }
   ]
  },
  {
   "title": "In Flight submissions",
   "type": "timeseries",
   "description": "Sequencer submissions currently running. Note this is at the level of a sequencer submission not a Daml transaction.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "submissions" } },
   "targets": [
    {
     "expr": "sum by(synchronizer, type, namespace, job, node) (daml_sequencer_client_submissions_in_flight{namespace=~\"$namespace\", job=~\"$job\", node=~\"$node\"})",
     "legendFormat": "{{namespace}} {{job}} {{node}} {{sync}} {{type}}"
    }
   ]
  },
  {
   "title": "Dropped Submissiones",
   "type": "timeseries",
   "description": "Submissions that were not sequenced",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "epm" } },
   "targets": [
    {
     "expr": "increase(daml_sequencer_client_submissions_dropped{namespace=~\"$namespace\",job=~\"$job\", node=~\"$node\"}[1m])",
     "legendFormat": "{{namespace}} {{job}} {{node}}"
    }
   ]
  },
  {
   "title": "Sequencer Client Batches ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "targets": [
    {
     "expr": "daml_sequencer_client_handler_max_in_flight_event_batches{namespace=~\"$namespace\",job=~\"$job\", node=~\"$node\"}",
     "legendFormat": "max {{namespace}} {{job}}"
    },
    {
     "expr": "daml_sequencer_client_handler_actual_in_flight_event_batches{namespace=~\"$namespace\",job=~\"$job\", node=~\"$node\"}",
     "legendFormat": "actual {{namespace}} {{job}}"
    }
   ]
  },
  {
   "title": "Events received",
   "type": "timeseries",
   "description": "Events received from the sequencer",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "epm" } },
   "targets": [
    {
     "expr": "rate(daml_sequencer_client_handler_sequencer_events{namespace=~\"$namespace\",job=~\"$job\", node=~\"$node\"}[$__rate_interval])",
     "legendFormat": "{{namespace}} {{job}} {{node}}"
    }
   ]
  }
 ]
}