{
 "title": "Sequencer Messages",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(daml_sequencer_block_events_total,namespace)"
    }
   },
   {
    "name": "job",
    "query": {
     "query": "label_values(daml_sequencer_block_events_total{namespace=\"$namespace\"},job)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Messages", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Last 24h messages / s",
   "type": "piechart",
   "description": "The average per second messages for the last 24h",
   "gridPos": { "h": 11, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(type) (rate(daml_sequencer_block_events_total{namespace=\"$namespace\", job=\"$job\"}[24h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sequencer Message Rate",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 17, "x": 7, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(daml_sequencer_block_events_total{namespace=\"$namespace\", job=\"$job\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(type) (rate(daml_sequencer_block_events_total{namespace=\"$namespace\", job=\"$job\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(daml_sequencer_block_events_total{namespace=\"$namespace\", job=\"$job\"}[1h]))",
     "legendFormat": "hourly total"
    },
    {
     "expr": "sum(rate(daml_sequencer_block_events_total{namespace=\"$namespace\", job=\"$job\"}[1h] offset 30d))",
     "legendFormat": "hourly total 30 days ago"
    }
   ]
  },
  {
   "title": "Confirmation Requests Rate by Member",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 20, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum by(member) (rate(daml_sequencer_block_events_total{namespace=\"$namespace\", job=\"$job\", type=\"send-confirmation-request\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Confirmation Requests by Member in the last Hour",
   "type": "table",
   "gridPos": { "h": 11, "w": 4, "x": 20, "y": 12 },
   "targets": [
    {
     "expr": "sort_desc(sum(delta(daml_sequencer_block_events_total{namespace=\"$namespace\",job=\"$job\",type=\"send-confirmation-request\"}[1h])) by (member))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Confirmation Responses Rate by Member",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 20, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "sum by(member) (rate(daml_sequencer_block_events_total{namespace=\"$namespace\", job=\"$job\", type=\"send-confirmation-response\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Confirmation Responses by Member in the last Hour",
   "type": "table",
   "gridPos": { "h": 11, "w": 4, "x": 20, "y": 23 },
   "targets": [
    {
     "expr": "sort_desc(sum(delta(daml_sequencer_block_events_total{namespace=\"$namespace\",job=\"$job\",type=\"send-confirmation-response\"}[1h])) by (member))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sequencer Message Rate by Participant",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "sum(rate(daml_sequencer_block_events_total{namespace=\"$namespace\", job=\"$job\",member=~\"PAR::.*\"}[$__rate_interval])) by (member)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sequencer Message Rate by Mediator",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "sum(rate(daml_sequencer_block_events_total{namespace=\"$namespace\", job=\"$job\",member=~\"MED::.*\"}[$__rate_interval])) by (member)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sequencer Message Rate by Member excluding Mediator/Participant",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 46 },
   "targets": [
    {
     "expr": "sum by(member) (rate(daml_sequencer_block_events_total{namespace=\"$namespace\", job=\"$job\", member!~\"(MED|PAR)::.*\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Message Bytes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "Sequencer Message Byte Rate",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(daml_sequencer_block_event_bytes_total{namespace=\"$namespace\", job=\"$job\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(type) (rate(daml_sequencer_block_event_bytes_total{namespace=\"$namespace\", job=\"$job\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(daml_sequencer_block_event_bytes_total{namespace=\"$namespace\", job=\"$job\"}[1h]))",
     "legendFormat": "hourly total"
    },
    {
     "expr": "sum(rate(daml_sequencer_block_event_bytes_total{namespace=\"$namespace\", job=\"$job\"}[1h] offset 30d))",
     "legendFormat": "hourly total 30 days ago"
    }
   ]
  },
  {
   "title": "Average Sequencer Message Size",
   "type": "timeseries",
   "description": "Average size per sequencer message in the last hour",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(increase(daml_sequencer_block_event_bytes_total{namespace=\"$namespace\", job=\"$job\"}[1h])) / sum(increase(daml_sequencer_block_events_total{namespace=\"$namespace\", job=\"$job\"}[1h]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(type) (increase(daml_sequencer_block_event_bytes_total{namespace=\"$namespace\", job=\"$job\"}[1h])) / sum by(type) (increase(daml_sequencer_block_events_total{namespace=\"$namespace\", job=\"$job\"}[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 100 Confirmation Requests Byte Rate by Member",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 20, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk(\n  100,\n  avg_over_time(\n    (\n      sum by(member) (\n        rate(daml_sequencer_block_event_bytes_total{namespace=\"$namespace\", job=\"$job\", type=\"send-confirmation-request\"}[$__rate_interval])\n      )\n    )[$__range:]\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}