{
 "title": "Sequencer Connection Pool",
 "description": "Metrics for the Canton sequencer connection pools, note that these are disabled by default as they are still under development so you will not see these metrics usually.",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(daml_sequencer_client_sequencer_connection_pool_connection_health,namespace)"
    }
   },
   {
    "name": "job",
    "query": {
     "query": "label_values(daml_sequencer_client_sequencer_connection_pool_connection_health,job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Health of a connection",
   "type": "state-timeline",
   "description": "Health of a connection (0: fatal, 1: failed, 2: validated). A failed connection is periodically retried for availability. A fatal subscription is considered invalid and will never be retried.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "max by (connection, namespace, job) (daml_sequencer_client_sequencer_connection_pool_connection_health{namespace=~\"$namespace\", job=~\"$job\"})",
     "legendFormat": "{{namespace}}:{{job}}:{{connection}}"
    }
   ]
  },
  {
   "title": "Health of a subscription",
   "type": "state-timeline",
   "description": "Health of a subscription (0: not used, 1: active). A subscription can be not used either because there are no more connections available, or because there are already enough subscriptions active (according to the trust threshold and liveness margin parameters).",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "max by (connection, namespace, job) (daml_sequencer_client_sequencer_connection_pool_subscription_health{namespace=~\"$namespace\",job=~\"$job\"})",
     "legendFormat": "{{namespace}}:{{job}}:{{connection}}"
    }
   ]
  },
  {
   "title": "Number of active subscriptions in the subscription pool",
   "type": "timeseries",
   "description": "This metric indicates the current number of subscriptions that are active.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "max by (namespace, job) (daml_sequencer_client_sequencer_connection_pool_active_subscriptions{namespace=~\"$namespace\",job=~\"$job\"})",
     "legendFormat": "{{namespace}}:{{job}}"
    }
   ]
  },
  {
   "title": "Number of connections validated by the connection pool",
   "type": "timeseries",
   "description": "This metric indicates the current number of connections that are up and validated. These connections are available for components of the node that need to communicate with the synchronizer.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "max by (namespace, job) (daml_sequencer_client_sequencer_connection_pool_validated_connections{namespace=~\"$namespace\",job=~\"$job\"})",
     "legendFormat": "{{namespace}}:{{job}}"
    }
   ]
  },
  {
   "title": "Sum of trust threshold and liveness margin configured in the subscription pool",
   "type": "timeseries",
   "description": "The liveness margin determines how many subscriptions on different sequencers are continuously maintained, beyond the minimum number defined by the trust threshold. In other words, the subscription pool will strive to maintain at all times (trust threshold + liveness margin)-many subscriptions active. This provides tolerance to subscriptions falling, enabling the node to continue operating while some sequencers are not used.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "max by (namespace, job) (daml_sequencer_client_sequencer_connection_pool_subscription_threshold{namespace=~\"$namespace\",job=~\"$job\"})",
     "legendFormat": "{{namespace}}:{{job}}"
    }
   ]
  },
  {
   "title": "Trust threshold configured in the connection pool",
   "type": "timeseries",
   "description": "The trust threshold determines how many connections to sequencers must be available and consistent (same synchronizer ID, same protocol version, same static parameters) for the connection pool to initialize. Furthermore, it also determines the number of sequencer subscriptions that must deliver identical copies of an event for that event to be accepted and processed by the node.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "max by (namespace, job) (daml_sequencer_client_sequencer_connection_pool_trust_threshold{namespace=~\"$namespace\",job=~\"$job\"})",
     "legendFormat": "{{namespace}}:{{job}}"
    }
   ]
  },
  {
   "title": "Number of connections tracked by the connection pool",
   "type": "timeseries",
   "description": "The configuration of the connection pool defines the parameters of the sequencer connections. This metrics shows the current number of those connections.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "max by (namespace, job)(daml_sequencer_client_sequencer_connection_pool_tracked_connections{namespace=~\"$namespace\",job=~\"$job\"})",
     "legendFormat": "{{namespace}}:{{job}}"
    }
   ]
  },
  {
   "title": "Number of gRPC requests sent on this connection",
   "type": "timeseries",
   "description": "This metric indicates the number of gRPC requests that have been sent on this connection.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sum by (connection, namespace, job)(rate(daml_sequencer_client_sequencer_connection_pool_grpc_requests{namespace=~\"$namespace\",job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "{{namespace}}:{{job}}:{{connection}}"
    }
   ]
  }
 ]
}