canton.participants.app-user {
  ledger-api{
    auth-services = [{
      type = unsafe-jwt-hmac-256
      target-audience = ${AUTH_APP_USER_AUDIENCE}
      secret = "unsafe"
    }]

    user-management-service.additional-admin-user-id = ${AUTH_APP_USER_VALIDATOR_USER_NAME}
  }
  # TODO(DACH-NY/canton-network-node#393) add admin API auth canton console supports proper client side config
}
