# This is deliberately lower than ConsoleCommandTimeout.defaultRequestTimeout
pekko.http.server.request-timeout = 38 seconds
pekko.http.server.parsing.error-handler="org.lfdecentralizedtrust.splice.http.PekkoHttpParsingErrorHandler$"
pekko.http.server.parsing.ignore-illegal-header-for =
  [ "accept-language"
    "authorization"
    "cookie"
    "origin"
    "proxy-authorization"
    "referer"
    "user-agent"
    "x-forwarded-for"
    "x-forwarded-host"
    "x-real-ip"
    "etag" ]
pekko.http.client.parsing.ignore-illegal-header-for = ["etag"]
# expose the remote address so that it can be used for per client IP rate limiting
# when no trusted X-Envoy-External-Address (nor X-Forwarded-For/X-Real-Ip) header is
# set by an upstream proxy
pekko.http.server.remote-address-attribute = on
