!include($SPLICE_ROOT/cluster/configs/shared/scratchnet.yaml)
multiValidator:
  postgresPvcSize: '1000Gi'
  requiresOnboardingSecret: true
loadTester:
  enable: true
  maxVUs: 300
  iterationsPerMinute: 1200
svs:
  sv-1: !include(sv.yaml) {}
  sv-2: !include(sv.yaml) {}
  sv-3: !include(sv.yaml) {}
  sv-4: !include(sv.yaml) {}
  sv-5: !include(sv.yaml) {}
  sv-6: !include(sv.yaml) {}
  sv-7: !include(sv.yaml) {}
  sv-8: !include(sv.yaml) {}
  sv-9: !include(sv.yaml) {}
  sv-10: !include(sv.yaml) {}
  sv-11: !include(sv.yaml) {}
  sv-12: !include(sv.yaml) {}
  sv-13: !include(sv.yaml) {}
  sv-14: !include(sv.yaml) {}
  sv-15: !include(sv.yaml) {}
  sv: !include(sv.yaml) {}
  sv-da-1: !include(sv.yaml) {}
persistentHeapDumps: true
chaosMesh:
  dabftLatency: 100ms
validators:
  party-allocator:
    postgresPvcSize: '200Gi'
    partyAllocator:
      enable: true
      maxParties: 500000
      parallelism: 4
      pvcSize: 100Gi
    namespace: party-allocator
    partyHint: 'digitalassset-partyallocator-1'
    onboardingSecret: 'eyJzcG9uc29yaW5nU3YiOiJEaWdpdGFsLUFzc2V0LTI6OjEyMjBmZWE2ZThlOGM5MmVmMWY3NmIwNTAxY2MzNWY2M2IyMzU2ZWEyY2VmYjkxOTA1MWJlMzcwZDRlYWJhZjljN2FiIiwic2VjcmV0IjoicjJDQ2l4dFdrb29taVk3MjVXR0xiWVBiMEorOE5GT1NVZDBHMTVaQ3lZST0iLCJwYXJ0eUhpbnQiOiJkaWdpdGFsYXNzc2V0LXBhcnR5YWxsb2NhdG9yLTEifQ=='
    participantPruningSchedule:
      cron: "0 /10 * * * ?" # Run every 10min
      maxDuration: "5m"
      retention: "14d"
    participant:
      resources:
        requests:
          memory: 16Gi
        limits:
          memory: 20Gi
      additionalEnvVars:
        - !include($SPLICE_ROOT/cluster/configs/shared/participant_pruning.yaml)
        - name: ADDITIONAL_CONFIG_TOPOLOGY_BATCH_SIZE
          value: |
            canton.participants.participant.topology.broadcast-batch-size = 50
    validatorApp:
      additionalEnvVars:
        - name: ADDITIONAL_CONFIG_DISABLE_TRANSFER_PREAPPROVAL_DEDUP
          value: |
            canton.validator-apps.validator_backend.transfer-preapproval.proposal-acceptance-deduplication = false
synchronizerMigration:
  frozenMigrationId: 0
  active:
    id: 0
    version: 0.6.11-snapshot.20260626.3244.0.vbc0c0fbf
    sequencer:
      enableBftSequencer: true
      dedicatedBftSequencerDb: false
      # migrateBftSequencerDbFromSharedServer: true
    releaseReference:
      gitReference: "refs/heads/tom-da/basicScratch"
      repoUrl: https://github.com/DACH-NY/canton-network-internal
      pulumiStacksDir: "cluster/stacks/scratchnets"
      pulumiBaseDir: "splice/cluster/pulumi"
      deploymentDir: "splice/cluster/deployment"
      spliceRoot: "splice"
      privateConfigsDir: "cluster/configs/configs-private"
      publicConfigsDir: "cluster/configs/configs"
