!include($SPLICE_ROOT/cluster/configs/shared/scratchnet.yaml)
multiValidator:
  postgresPvcSize: '1000Gi'
  requiresOnboardingSecret: true
loadTester:
  enable: true
  maxVUs: 300
  iterationsPerMinute: 1800
svs:
  sv-1: !include(sv.yaml) {}
  sv-2: !include(sv.yaml) {}
  sv-3: !include(sv.yaml) {}
  sv-4: !include(sv.yaml) {}
  sv-5: !include(sv.yaml) {}
  sv-6: !include(sv.yaml) {}
  sv-7: !include(sv.yaml) {}
  sv-8: !include(sv.yaml) {}
  sv-9: !include(sv.yaml) {}
  sv-10: !include(sv.yaml) {}
  sv-11: !include(sv.yaml) {}
  sv-12: !include(sv.yaml) {}
  sv-13: !include(sv.yaml) {}
  sv-14: !include(sv.yaml) {}
  sv-15: !include(sv.yaml) {}
  sv: !include(sv.yaml) {}
  sv-da-1: !include(sv.yaml) {}
persistentHeapDumps: true
chaosMesh:
  dabftLatency: 50ms
synchronizerMigration:
  lsuEnabled: true
  frozenMigrationId: 0
  active:
    id: 0
    version: 0.6.6-snapshot.20260527.2829.0.v72a921da
    sequencer:
      enableBftSequencer: true
    releaseReference:
      gitReference: "refs/heads/tom-da/basicScratch"
      repoUrl: https://github.com/DACH-NY/canton-network-internal
      pulumiStacksDir: "cluster/stacks/scratchnets"
      pulumiBaseDir: "splice/cluster/pulumi"
      deploymentDir: "splice/cluster/deployment"
      spliceRoot: "splice"
      privateConfigsDir: "cluster/configs/configs-private"
      publicConfigsDir: "cluster/configs/configs"
    enableLogicalSynchronizerDeploymentMode: true
