rateLimits:
  /registry/:
    name: token-registry
    type: limited
    maxTokens: 6000
    tokensPerFill: 6000
    fillInterval: 60s
    perIpLimits:
      maxTokens: 600
      tokensPerFill: 600
      fillInterval: 60s
