{
 "title": "Cache Performance Dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(daml_cache_hits, namespace)"
    }
   },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(daml_cache_hits{namespace=~\"$namespace\"},job)"
    }
   },
   {
    "name": "component",
    "label": "Component",
    "query": {
     "query": "label_values(daml_cache_hits{namespace=~\"$namespace\", job=~\"$job\"},component)"
    }
   },
   {
    "name": "cache",
    "label": "Cache",
    "query": {
     "query": "label_values(daml_cache_hits{namespace=~\"$namespace\", job=~\"$job\"},cache)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cache Hit Ratio",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (cache, namespace, job) (increase(daml_cache_hits{cache=~\"$cache\", namespace=~\"$namespace\", job=~\"$job\"}[$__rate_interval])) / (sum by (cache, namespace, job) (increase(daml_cache_hits{cache=~\"$cache\", namespace=~\"$namespace\", job=~\"$job\"}[$__rate_interval])) + sum by (cache, namespace, job) (increase(daml_cache_misses{cache=~\"$cache\", namespace=~\"$namespace\", job=~\"$job\"}[$__rate_interval]))) * 100",
     "legendFormat": "Hit Ratio {{ namespace }} {{ job }} {{ cache }}"
    }
   ]
  },
  {
   "title": "Cache Hit Rate",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (cache, namespace, job) (rate(daml_cache_hits{cache=~\"$cache\", namespace=~\"$namespace\", job=~\"$job\"}[$__rate_interval])) ",
     "legendFormat": "Hit Ratio {{ namespace }} {{ job }} {{ cache }}"
    }
   ]
  },
  {
   "title": "Total Cache Size",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "elements" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (cache, namespace, job) (daml_cache_size{cache=~\"$cache\", namespace=~\"$namespace\", job=~\"$job\"})",
     "legendFormat": "Total Size {{ namespace }} {{ job }} {{ cache }}"
    }
   ]
  },
  {
   "title": "Rate of Cache Evictions (5m)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(daml_cache_evictions{cache=~\"$cache\", namespace=~\"$namespace\", job=~\"$job\"}[5m])",
     "legendFormat": "Eviction Rate {{ namespace }} {{ job }} {{ cache }}"
    }
   ]
  },
  {
   "title": "Eviction percentage over ${__rate_interval} ",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (cache, namespace, job) (increase(daml_cache_evictions{cache=~\"$cache\", namespace=~\"$namespace\", job=~\"$job\"}[$__rate_interval])) / max by (cache, namespace, job) (daml_cache_size{cache=~\"$cache\", namespace=~\"$namespace\", job=~\"$job\"})",
     "legendFormat": "Eviction Rate/Size {{ namespace }} {{ job }} {{ cache }}"
    }
   ]
  },
  {
   "title": "Cache Miss Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (cache, namespace, job) (rate(daml_cache_misses{cache=~\"$cache\", namespace=~\"$namespace\", job=~\"$job\"}[$__rate_interval])) ",
     "legendFormat": "Hit Ratio {{ namespace }} {{ job }} {{ cache }}"
    }
   ]
  }
 ]
}