{
 "title": "Http Server",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(daml_http_requests_duration_seconds,namespace)"
    }
   },
   {
    "name": "job",
    "query": {
     "query": "label_values(daml_http_requests_duration_seconds{namespace=~\"$namespace\"},job)"
    }
   },
   {
    "name": "service",
    "query": {
     "query": "label_values(daml_http_requests_duration_seconds{namespace=~\"$namespace\", job=~\"$job\"},http_service)"
    }
   },
   {
    "name": "operation",
    "query": {
     "query": "label_values(daml_http_requests_duration_seconds{namespace=~\"$namespace\", job=~\"$job\", http_service=~\"$service\"},operation)"
    }
   },
   { "name": "percentile", "query": "0.9,0.95,0.99" }
  ]
 },
 "panels": [
  {
   "title": "Handled Requests",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 15, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "label_replace(histogram_count(rate(daml_http_requests_duration_seconds{namespace=~\"$namespace\", job=~\"$job\", http_service=~\"$service\", operation=~\"$operation\", status_code=~\"2.*\"}[$__rate_interval])), \"source_display\", \"Source UI: $1\", \"source_ui\", \"(.+)\")",
     "legendFormat": "{{namespace}} {{job}} {{http_service}} {{operation}} {{status_code}} {{source_display}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "histogram_count(rate(daml_http_requests_duration_seconds{namespace=~\"$namespace\", job=~\"$job\", http_service=~\"$service\", operation=~\"$operation\", status_code!~\"2.*\"}[$__rate_interval]))",
     "legendFormat": "{{namespace}} {{job}} {{http_service}} {{operation}} {{status_code}}"
    }
   ]
  },
  {
   "title": "Request Timing quantile $percentile",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($percentile, rate(daml_http_requests_duration_seconds{namespace=~\"$namespace\", job=~\"$job\", http_service=~\"$service\", operation=~\"$operation\"}[$__rate_interval]))",
     "legendFormat": "{{namespace}} {{job}} {{http_service}} {{operation}} {{status_code}}"
    }
   ]
  },
  {
   "title": "In Flight Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "requests" } },
   "targets": [
    {
     "expr": "daml_http_requests_inflight{namespace=~\"$namespace\", job=~\"$job\", http_service=~\"$service\", operation=~\"$operation\"}",
     "legendFormat": "{{namespace}} {{job}} {{http_service}} {{operation}} {{status_code}}"
    }
   ]
  }
 ]
}