{
 "title": "Splice Rate Limiting",
 "tags": [
  "prometheus",
  "rate-limiting"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(splice_rate_limiting_total, namespace)"
    }
   },
   {
    "name": "node_name",
    "label": "Node Name",
    "query": {
     "query": "label_values(splice_rate_limiting_total{namespace=~\"$namespace\"},node_name)"
    }
   },
   {
    "name": "http_service",
    "label": "HTTP Service",
    "query": {
     "query": "label_values(splice_rate_limiting_total{namespace=~\"$namespace\", node_name=~\"$node_name\"},http_service)"
    }
   },
   {
    "name": "limiter",
    "label": "Limiter",
    "query": {
     "query": "label_values(splice_rate_limiting_total{namespace=~\"$namespace\", http_service=~\"$http_service\", node_name=~\"$node_name\"},limiter)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total Rejections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(splice_rate_limiting_total{namespace=~\"$namespace\", http_service=~\"$http_service\", limiter=~\"$limiter\", node_name=~\"$node_name\", result!=\"accepted\"}[$__rate_interval])) by (result)",
     "legendFormat": "{{ result }}"
    }
   ]
  },
  {
   "title": "Total Requests by Result",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(splice_rate_limiting_total{namespace=~\"$namespace\", http_service=~\"$http_service\", limiter=~\"$limiter\", node_name=~\"$node_name\"}[$__range])) by (result)",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(splice_rate_limiting_total{namespace=~\"$namespace\", http_service=~\"$http_service\", limiter=~\"$limiter\", node_name=~\"$node_name\"}[$__rate_interval])) by (limiter, limiter_type, limiter_attribute)",
     "legendFormat": "{{ limiter }} {{limiter_type}} {{limiter_attribute}}"
    }
   ]
  },
  {
   "title": "Rejections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(splice_rate_limiting_total{namespace=~\"$namespace\", http_service=~\"$http_service\", limiter=~\"$limiter\", node_name=~\"$node_name\", result!=\"accepted\"}[$__rate_interval])) by (result, limiter, limiter_type, limiter_attribute)",
     "legendFormat": "{{ limiter }} {{limiter_type}} {{limiter_attribute}}"
    }
   ]
  },
  {
   "title": "Limits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "splice_rate_limiting_max_limit_per_second{namespace=~\"$namespace\", node_name=~\"$node_name\", http_service=~\"$http_service\", limiter=~\"$limiter\"}",
     "legendFormat": "{{ limiter }} {{limiter_type}}{{limiter_attribute}}"
    }
   ]
  },
  {
   "title": "Attribute Limits not enforced",
   "type": "timeseries",
   "description": "Cannot extract the attribute value",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(splice_rate_limiting_unknown_attribute_not_limited_total{namespace=~\"$namespace\", http_service=~\"$http_service\", limiter=~\"$limiter\", node_name=~\"$node_name\"}[$__rate_interval])) by (limiter, limiter_type, limiter_attribute)",
     "legendFormat": "{{ limiter }} {{limiter_type}} {{limiter_attribute}}"
    }
   ]
  }
 ]
}