{
 "title": "Cache Performance Dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(daml_cache_hits, namespace)"
    }
   },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(daml_cache_hits{namespace=~\"$namespace\"},job)"
    }
   },
   {
    "name": "component",
    "label": "Component",
    "query": {
     "query": "label_values(daml_cache_hits{namespace=~\"$namespace\", job=~\"$job\"},component)"
    }
   },
   {
    "name": "cache",
    "label": "Cache",
    "query": {
     "query": "label_values(daml_cache_hits{namespace=~\"$namespace\", job=~\"$job\"},cache)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cache Hit Ratio",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (cache, namespace, job) (increase(daml_cache_hits{cache=~\"$cache\", namespace=~\"$namespace\", job=~\"$job\"}[$__rate_interval])) / (sum by (cache, namespace, job) (increase(daml_cache_hits{cache=~\"$cache\", namespace=~\"$namespace\", job=~\"$job\"}[$__rate_interval])) + sum by (cache, namespace, job) (increase(daml_cache_misses{cache=~\"$cache\", namespace=~\"$namespace\", job=~\"$job\"}[$__rate_interval]))) * 100",
     "legendFormat": "Hit Ratio {{ namespace }} {{ job }} {{ cache }}"
    }
   ]
  },
  {
   "title": "Cache Hit Rate",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (cache, namespace, job) (rate(daml_cache_hits{cache=~\"$cache\", namespace=~\"$namespace\", job=~\"$job\"}[$__rate_interval])) ",
     "legendFormat": "Hit Ratio {{ namespace }} {{ job }} {{ cache }}"
    }
   ]
  },
  {
   "title": "Total Cache Size",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "elements" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (cache, namespace, job) (daml_cache_size{cache=~\"$cache\", namespace=~\"$namespace\", job=~\"$job\"})",
     "legendFormat": "Total Size {{ namespace }} {{ job }} {{ cache }}"
    }
   ]
  },
  {
   "title": "Rate of Cache Evictions (5m)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(daml_cache_evictions{cache=~\"$cache\", namespace=~\"$namespace\", job=~\"$job\"}[5m])",
     "legendFormat": "Eviction Rate {{ namespace }} {{ job }} {{ cache }}"
    }
   ]
  },
  {
   "title": "Eviction percentage over ${__rate_interval} ",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (cache, namespace, job) (increase(daml_cache_evictions{cache=~\"$cache\", namespace=~\"$namespace\", job=~\"$job\"}[$__rate_interval])) / max by (cache, namespace, job) (daml_cache_size{cache=~\"$cache\", namespace=~\"$namespace\", job=~\"$job\"})",
     "legendFormat": "Eviction Rate/Size {{ namespace }} {{ job }} {{ cache }}"
    }
   ]
  },
  {
   "title": "Cache Miss Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (cache, namespace, job) (rate(daml_cache_misses{cache=~\"$cache\", namespace=~\"$namespace\", job=~\"$job\"}[$__rate_interval])) ",
     "legendFormat": "Hit Ratio {{ namespace }} {{ job }} {{ cache }}"
    }
   ]
  }
 ]
}
{
 "title": "Pulumi Operator Stacks Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "stack",
    "query": {
     "query": "label_values(splice_deployment_pulumi_stack_condition,stack)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Stack CR", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "State",
   "type": "state-timeline",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "splice_deployment_pulumi_stack_status",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Conditions $stack",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "repeat": "stack",
   "targets": [
    {
     "expr": "splice_deployment_pulumi_stack_condition{stack=~\"${stack}\"}",
     "legendFormat": "{{stack}} {{reason}} {{type}} {{state}}"
    }
   ]
  }
 ]
}
{
 "title": "gRPC Endpoints",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(daml_grpc_server_started_total, namespace)"
    }
   },
   {
    "name": "component",
    "query": {
     "query": "label_values(daml_grpc_server_started_total{namespace=\"$namespace\"}, service)"
    }
   },
   {
    "name": "service",
    "query": {
     "query": "label_values(daml_grpc_server_started_total{namespace=\"$namespace\", service=\"$component\"}, grpc_service_name)"
    }
   },
   {
    "name": "method",
    "query": {
     "query": "label_values(daml_grpc_server_started_total{namespace=\"$namespace\", service=\"$component\",grpc_service_name=~\"$service\"}, grpc_method_name)"
    }
   },
   { "name": "datasource", "query": "prometheus" },
   { "name": "quantile", "query": "0.5,0.9,0.95,0.99" }
  ]
 },
 "panels": [
  {
   "title": "Latency Quantile",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($quantile, sum by(grpc_service_name, grpc_client_type, grpc_method_name, grpc_server_type, grpc_code) (rate(daml_grpc_server_duration_seconds{namespace=\"$namespace\", service=\"$component\", grpc_service_name=~\"$service\", grpc_method_name=~\"$method\"}[$__rate_interval])))",
     "legendFormat": "{{grpc_method_name}} - {{grpc_code}} ({{grpc_client_type}} - {{grpc_server_type}})"
    }
   ]
  },
  {
   "title": "Requests Started",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(grpc_server_type, grpc_service_name, grpc_client_type, grpc_method_name) (rate(daml_grpc_server_started_total{namespace=\"$namespace\", service=\"$component\", grpc_service_name=~\"$service\", grpc_method_name=~\"$method\"}[$__rate_interval]))",
     "legendFormat": "{{grpc_method_name}}  ({{grpc_client_type}} - {{grpc_server_type}}) "
    }
   ]
  },
  {
   "title": "Requests Finished",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(grpc_server_type, grpc_service_name, grpc_client_type, grpc_method_name, grpc_code) (rate(daml_grpc_server_handled_total{namespace=\"$namespace\", service=\"$component\", grpc_service_name=~\"$service\", grpc_method_name=~\"$method\"}[$__rate_interval]))",
     "legendFormat": "{{grpc_method_name}} - {{grpc_code}} -  ({{grpc_client_type}} - {{grpc_server_type}}) "
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(grpc_server_type, grpc_service_name, grpc_client_type, grpc_method_name, grpc_code) (rate(daml_grpc_server_handled_total{namespace=\"$namespace\", service=\"$component\", grpc_service_name=~\"$service\", grpc_method_name=~\"$method\", grpc_code!=\"OK\"}[$__rate_interval]))",
     "legendFormat": "{{grpc_method_name}} - {{grpc_code}}"
    }
   ]
  },
  {
   "title": "Error Distribution",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(service, grpc_server_type, grpc_service_name, grpc_client_type, grpc_method_name, grpc_code) (rate(daml_grpc_server_handled_total{namespace=\"$namespace\", service=\"$component\", grpc_service_name=~\"$service\", grpc_method_name=~\"$method\", grpc_code!=\"OK\"}[1m])) / on(service, grpc_server_type, grpc_service_name, grpc_client_type, grpc_method_name) group_left() sum by(service, grpc_server_type, grpc_service_name, grpc_client_type, grpc_method_name) (rate(daml_grpc_server_handled_total{namespace=\"$namespace\", service=\"$component\", grpc_service_name=~\"$service\", grpc_method_name=~\"$method\"}[1m]))",
     "legendFormat": "{{grpc_method_name}} -- {{grpc_code}}"
    }
   ]
  },
  {
   "title": "Average Request Payload Size",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(grpc_server_type, grpc_service_name, grpc_client_type, grpc_method_name) (histogram_avg(rate(daml_grpc_server_messages_received_bytes{namespace=\"$namespace\", service=\"$component\", grpc_service_name=~\"$service\", grpc_method_name=~\"$method\"}[$__rate_interval])))",
     "legendFormat": "{{grpc_method_name}} - ({{grpc_client_type}} - {{grpc_server_type}})"
    }
   ]
  },
  {
   "title": "Request Payload Throughput",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(grpc_server_type, grpc_service_name, grpc_client_type, grpc_method_name) (histogram_sum(rate(daml_grpc_server_messages_received_bytes{namespace=\"$namespace\", service=\"$component\", grpc_service_name=~\"$service\", grpc_method_name=~\"$method\"}[$__rate_interval])))",
     "legendFormat": "{{grpc_method_name}} - ({{grpc_client_type}} - {{grpc_server_type}})"
    }
   ]
  }
 ]
}
{
 "title": "Health",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(daml_health_status, namespace)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(daml_health_status{namespace=\"$namespace\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Components' Status",
   "type": "status-history",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "daml_health_status{namespace=\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "{{pod}} {{component}}"
    }
   ]
  }
 ]
}
{
 "title": "Http Server",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(daml_http_requests_duration_seconds,namespace)"
    }
   },
   {
    "name": "job",
    "query": {
     "query": "label_values(daml_http_requests_duration_seconds{namespace=~\"$namespace\"},job)"
    }
   },
   {
    "name": "service",
    "query": {
     "query": "label_values(daml_http_requests_duration_seconds{namespace=~\"$namespace\", job=~\"$job\"},http_service)"
    }
   },
   {
    "name": "operation",
    "query": {
     "query": "label_values(daml_http_requests_duration_seconds{namespace=~\"$namespace\", job=~\"$job\", http_service=~\"$service\"},operation)"
    }
   },
   { "name": "percentile", "query": "0.9,0.95,0.99" }
  ]
 },
 "panels": [
  {
   "title": "Handled Requests",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 15, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "label_replace(histogram_count(rate(daml_http_requests_duration_seconds{namespace=~\"$namespace\", job=~\"$job\", http_service=~\"$service\", operation=~\"$operation\", status_code=~\"2.*\"}[$__rate_interval])), \"source_display\", \"Source UI: $1\", \"source_ui\", \"(.+)\")",
     "legendFormat": "{{namespace}} {{job}} {{http_service}} {{operation}} {{status_code}} {{source_display}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "histogram_count(rate(daml_http_requests_duration_seconds{namespace=~\"$namespace\", job=~\"$job\", http_service=~\"$service\", operation=~\"$operation\", status_code!~\"2.*\"}[$__rate_interval]))",
     "legendFormat": "{{namespace}} {{job}} {{http_service}} {{operation}} {{status_code}}"
    }
   ]
  },
  {
   "title": "Request Timing quantile $percentile",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($percentile, rate(daml_http_requests_duration_seconds{namespace=~\"$namespace\", job=~\"$job\", http_service=~\"$service\", operation=~\"$operation\"}[$__rate_interval]))",
     "legendFormat": "{{namespace}} {{job}} {{http_service}} {{operation}} {{status_code}}"
    }
   ]
  },
  {
   "title": "In Flight Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "requests" } },
   "targets": [
    {
     "expr": "daml_http_requests_inflight{namespace=~\"$namespace\", job=~\"$job\", http_service=~\"$service\", operation=~\"$operation\"}",
     "legendFormat": "{{namespace}} {{job}} {{http_service}} {{operation}} {{status_code}}"
    }
   ]
  }
 ]
}
{
 "title": "Http Client",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(daml_http_client_requests_duration_seconds,namespace)"
    }
   },
   {
    "name": "job",
    "query": {
     "query": "label_values(daml_http_client_requests_duration_seconds{namespace=~\"$namespace\"},job)"
    }
   },
   {
    "name": "operation",
    "query": {
     "query": "label_values(daml_http_client_requests_duration_seconds{namespace=~\"$namespace\", job=~\"$job\", http_client=~\"$http_client\"},operation)"
    }
   },
   {
    "name": "http_client",
    "query": {
     "query": "label_values(daml_http_client_requests_duration_seconds{namespace=~\"$namespace\", job=~\"$job\"},http_client)"
    }
   },
   { "name": "percentile", "query": "0.9,0.95,0.99" },
   { "name": "filter" }
  ]
 },
 "panels": [
  {
   "title": "Client requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "histogram_count(rate(daml_http_client_requests_duration_seconds{namespace=~\"$namespace\", job=~\"$job\", operation=~\"$operation\", status_code=~\"2.*\"}[$__rate_interval]))",
     "legendFormat": "{{namespace}} {{job}} {{target_host}} {{http_client}} {{operation}} {{status_code}}"
    }
   ]
  },
  {
   "title": "Client Requests Timing quantile 0.95 ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($percentile, rate(daml_http_client_requests_duration_seconds{namespace=~\"$namespace\", job=~\"$job\", http_client=~\"$http_client\", operation=~\"$operation\"}[$__rate_interval]))",
     "legendFormat": "{{namespace}} {{job}} {{target_host}} {{http_client}} {{operation}} {{status_code}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 15, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "histogram_count(rate(daml_http_client_requests_duration_seconds{namespace=~\"$namespace\", job=~\"$job\", operation=~\"$operation\", status_code!~\"2.*\"}[$__rate_interval]))",
     "legendFormat": "{{namespace}} {{job}} {{http_client}} {{target_host}} {{operation}} {{status}} {{status_code}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "table",
   "gridPos": { "h": 11, "w": 9, "x": 15, "y": 17 },
   "targets": [
    {
     "expr": "sum by(namespace, job, http_client, operation, status_code, target_host) (histogram_count(increase(daml_http_client_requests_duration_seconds{namespace=~\"$namespace\", job=~\"$job\", operation=~\"$operation\", status_code!~\"2.*\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "In Flight Client Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "daml_http_client_requests_inflight{namespace=~\"$namespace\", job=~\"$job\", http_client=~\"$http_client\", operation=~\"$operation\"}\n",
     "legendFormat": "{{namespace}} {{job}} {{target_host}} {{http_client}} {{operation}} {{status_code}}"
    }
   ]
  }
 ]
}
{
 "title": "Istio Rate Limiting",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "query": { "query": "label_values(namespace)" } }
  ]
 },
 "panels": [
  {
   "title": "Istio total rejected requests",
   "type": "timeseries",
   "description": "Rate of rejected requests per second, broken down by the namespace reporting the request and the destination service receiving it. Rejections are HTTP 429 (Too Many Requests) responses, or, for gRPC calls (e.g. the sequencer API), RESOURCE_EXHAUSTED (grpc_response_status 8) responses, which envoy returns with HTTP 200.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(namespace, destination_service) (rate(istio_requests_total{response_code=\"429\", namespace=~\"$namespace\"}[$__rate_interval])) + sum by(namespace, destination_service) (rate(istio_requests_total{grpc_response_status=\"8\", namespace=~\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rejection ratio",
   "type": "timeseries",
   "description": "Fraction of the Envoy local rate limit evaluations that were rejected (HTTP 429, or gRPC RESOURCE_EXHAUSTED for gRPC APIs such as the sequencer), per namespace, pod and limiter. One filter per limit is installed (limiter=global, per_ip, endpoint_per_ip) and every request is evaluated by each of them.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(envoy_http_local_rate_limit_enforced{namespace=~\"$namespace\"}[$__rate_interval])) by (namespace, pod, limiter)\n/\nsum(rate(envoy_http_local_rate_limit_enabled{namespace=~\"$namespace\"}[$__rate_interval])) by (namespace, pod, limiter)",
     "legendFormat": "{{namespace}} - {{pod}} - {{limiter}}"
    }
   ]
  },
  {
   "title": "Enforced requests",
   "type": "timeseries",
   "description": "Rate of number of requests for which rate limiting was applied (HTTP 429, or gRPC RESOURCE_EXHAUSTED for gRPC APIs such as the sequencer), broken down by the limit that rejected them: global, per_ip (per client IP) and endpoint_per_ip (per endpoint and client IP).",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(envoy_http_local_rate_limit_enforced{namespace=~\"$namespace\"}[$__rate_interval])) by (namespace, pod, limiter)",
     "legendFormat": "{{namespace}} - {{pod}} - {{limiter}}"
    }
   ]
  },
  {
   "title": "Rejected requests",
   "type": "timeseries",
   "description": "Rate for responses without an available token (but not necessarily enforced)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(envoy_http_local_rate_limit_rate_limited{namespace=~\"$namespace\"}[$__rate_interval])) by (namespace, job, limiter)",
     "legendFormat": "{{namespace}} - {{job}} - {{limiter}}"
    }
   ]
  },
  {
   "title": "Enabled requests",
   "type": "timeseries",
   "description": "Rate for number of requests for which the rate limiter was consulted",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(envoy_http_local_rate_limit_enabled{namespace=~\"$namespace\"}[$__rate_interval])) by (namespace, pod, limiter)",
     "legendFormat": "{{namespace}} - {{pod}} - {{limiter}}"
    }
   ]
  },
  {
   "title": "Allowed requests",
   "type": "timeseries",
   "description": "Rate for number of requests under limit responses from the token bucket",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(envoy_http_local_rate_limit_ok{namespace=~\"$namespace\"}[$__rate_interval])) by (namespace, pod, limiter)",
     "legendFormat": "{{namespace}} - {{pod}} - {{limiter}}"
    }
   ]
  }
 ]
}
{
 "title": "Splice Rate Limiting",
 "tags": [
  "prometheus",
  "rate-limiting"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(splice_rate_limiting_total, namespace)"
    }
   },
   {
    "name": "node_name",
    "label": "Node Name",
    "query": {
     "query": "label_values(splice_rate_limiting_total{namespace=~\"$namespace\"},node_name)"
    }
   },
   {
    "name": "http_service",
    "label": "HTTP Service",
    "query": {
     "query": "label_values(splice_rate_limiting_total{namespace=~\"$namespace\", node_name=~\"$node_name\"},http_service)"
    }
   },
   {
    "name": "limiter",
    "label": "Limiter",
    "query": {
     "query": "label_values(splice_rate_limiting_total{namespace=~\"$namespace\", http_service=~\"$http_service\", node_name=~\"$node_name\"},limiter)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total Rejections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(splice_rate_limiting_total{namespace=~\"$namespace\", http_service=~\"$http_service\", limiter=~\"$limiter\", node_name=~\"$node_name\", result!=\"accepted\"}[$__rate_interval])) by (result)",
     "legendFormat": "{{ result }}"
    }
   ]
  },
  {
   "title": "Total Requests by Result",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(splice_rate_limiting_total{namespace=~\"$namespace\", http_service=~\"$http_service\", limiter=~\"$limiter\", node_name=~\"$node_name\"}[$__range])) by (result)",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(splice_rate_limiting_total{namespace=~\"$namespace\", http_service=~\"$http_service\", limiter=~\"$limiter\", node_name=~\"$node_name\"}[$__rate_interval])) by (limiter, limiter_type, limiter_attribute)",
     "legendFormat": "{{ limiter }} {{limiter_type}} {{limiter_attribute}}"
    }
   ]
  },
  {
   "title": "Rejections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(splice_rate_limiting_total{namespace=~\"$namespace\", http_service=~\"$http_service\", limiter=~\"$limiter\", node_name=~\"$node_name\", result!=\"accepted\"}[$__rate_interval])) by (result, limiter, limiter_type, limiter_attribute)",
     "legendFormat": "{{ limiter }} {{limiter_type}} {{limiter_attribute}}"
    }
   ]
  },
  {
   "title": "Limits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "splice_rate_limiting_max_limit_per_second{namespace=~\"$namespace\", node_name=~\"$node_name\", http_service=~\"$http_service\", limiter=~\"$limiter\"}",
     "legendFormat": "{{ limiter }} {{limiter_type}}{{limiter_attribute}}"
    }
   ]
  },
  {
   "title": "Attribute Limits not enforced",
   "type": "timeseries",
   "description": "Cannot extract the attribute value",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(splice_rate_limiting_unknown_attribute_not_limited_total{namespace=~\"$namespace\", http_service=~\"$http_service\", limiter=~\"$limiter\", node_name=~\"$node_name\"}[$__rate_interval])) by (limiter, limiter_type, limiter_attribute)",
     "legendFormat": "{{ limiter }} {{limiter_type}} {{limiter_attribute}}"
    }
   ]
  }
 ]
}