{
 "title": "JVM Executor Services",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(daml_executor_pool_size, namespace)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(daml_executor_pool_size{namespace=\"$namespace\"}, pod)"
    }
   },
   {
    "name": "container",
    "query": {
     "query": "label_values(daml_executor_pool_size{namespace=\"$namespace\", pod=~\"$pod\"}, container)"
    }
   },
   {
    "name": "name",
    "query": {
     "query": "label_values(daml_executor_pool_size{namespace=\"$namespace\", pod=~\"$pod\",container=\"$container\"}, name)"
    }
   },
   {
    "name": "group_without",
    "query": "endpoint, instance,daml_version,job,namespace,container,canton_version"
   }
  ]
 },
 "panels": [
  { "title": "Runtime Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Task Run Duration (p95}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(namespace, pod, container, name, component, participant) (rate(daml_executor_runtime_duration_seconds{namespace=\"$namespace\", pod=~\"$pod\", container=\"$container\", name=~\"$name\"}[$__rate_interval])))",
     "legendFormat": "{{pod}} - {{container}} - {{name}} / {{component}} {{participant}}"
    }
   ]
  },
  {
   "title": "Task Run Duration (average}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum without() (histogram_avg(rate(daml_executor_runtime_duration_seconds{namespace=\"$namespace\", pod=~\"$pod\", container=\"$container\", name=~\"$name\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Task Idle Duration (p95}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(namespace, pod, container, name, component, participant) (rate(daml_executor_runtime_idle_duration_seconds{namespace=\"$namespace\", pod=~\"$pod\", container=\"$container\", name=~\"$name\"}[$__rate_interval])))",
     "legendFormat": "{{pod}} - {{container}} - {{name}} / {{component}} {{participant}}"
    }
   ]
  },
  {
   "title": "Task Idle Duration (average}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum without() (histogram_avg(rate(daml_executor_runtime_idle_duration_seconds{namespace=\"$namespace\", pod=~\"$pod\", container=\"$container\", name=~\"$name\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Submitted Tasks",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "tasks / s" } },
   "targets": [
    {
     "expr": "sum without($group_without) (rate(daml_executor_runtime_submitted_total{namespace=\"$namespace\", pod=~\"$pod\", container=\"$container\", name=~\"$name\"}[$__rate_interval]))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Completed Tasks",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "tasks / s" } },
   "targets": [
    {
     "expr": "sum without($group_without) (rate(daml_executor_runtime_completed_total{namespace=\"$namespace\", pod=~\"$pod\", container=\"$container\", name=~\"$name\"}[$__rate_interval]))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Running Tasks",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum without($group_without) (daml_executor_runtime_running{namespace=\"$namespace\", pod=~\"$pod\", container=\"$container\", name=~\"$name\"})\n",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Common Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Info",
   "type": "text",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 43 },
   "options": {
    "content": "# Common Executor Service Metrics\n\nExecutor Service Metrics that are common between thread pools and fork join pools.\nThese metrics are outsourced from the Executor Service itself."
   }
  },
  {
   "title": "Pool Size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "daml_executor_pool_size{namespace=\"$namespace\", pod=~\"$pod\", container=\"$container\", name=~\"$name\"}",
     "legendFormat": "{{pod}} -- {{name}} -- {{type}}"
    }
   ]
  },
  {
   "title": "Active Threads",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 58 },
   "targets": [
    {
     "expr": "daml_executor_threads_active{namespace=\"$namespace\", pod=~\"$pod\", container=\"$container\", name=~\"$name\"}",
     "legendFormat": "{{pod}} -- {{name}} -- {{type}}"
    }
   ]
  },
  {
   "title": "Queued Tasks",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 67 },
   "targets": [
    {
     "expr": "daml_executor_tasks_queued{namespace=\"$namespace\", pod=~\"$pod\", container=\"$container\", name=~\"$name\"}",
     "legendFormat": "{{pod}} -- {{name}} -- {{type}}"
    }
   ]
  },
  { "title": "Thread Pool Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 } },
  {
   "title": "Pool Sizes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 77 },
   "targets": [
    {
     "expr": "daml_executor_pool_core{namespace=\"$namespace\", pod=~\"$pod\", container=\"$container\", name=~\"$name\"}",
     "legendFormat": "Core - {{pod}} -- {{name}} -- {{type}}"
    },
    {
     "expr": "daml_executor_pool_max{namespace=\"$namespace\", pod=~\"$pod\", container=\"$container\", name=~\"$name\"}",
     "legendFormat": "Max - {{pod}} -- {{name}} -- {{type}}"
    },
    {
     "expr": "daml_executor_pool_largest{namespace=\"$namespace\", pod=~\"$pod\", container=\"$container\", name=~\"$name\"}",
     "legendFormat": "Largest - {{pod}} -- {{name}} -- {{type}}"
    }
   ]
  },
  {
   "title": "Tasks Submitted",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "tasks/s" } },
   "targets": [
    {
     "expr": "sum without($group_without) (rate(daml_executor_tasks_submitted{namespace=\"$namespace\", pod=~\"$pod\", container=\"$container\", name=~\"$name\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tasks Completed",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "tasks/s" } },
   "targets": [
    {
     "expr": "sum without($group_without) (rate(daml_executor_tasks_completed{namespace=\"$namespace\", pod=~\"$pod\", container=\"$container\", name=~\"$name\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Remaining Queue Capacity",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 104 },
   "targets": [
    {
     "expr": "daml_executor_tasks_queue_remaining{namespace=\"$namespace\", pod=~\"$pod\", container=\"$container\", name=~\"$name\"}",
     "legendFormat": "Remaining - {{pod}} -- {{name}} -- {{type}}"
    }
   ]
  },
  { "title": "Fork Join Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 113 } },
  {
   "title": "Running Threads",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 114 },
   "targets": [
    {
     "expr": "daml_executor_threads_running{namespace=\"$namespace\", pod=~\"$pod\", container=\"$container\", name=~\"$name\"}",
     "legendFormat": "{{pod}} -- {{name}} -- {{type}}"
    }
   ]
  },
  {
   "title": "Stolen Tasks",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 123 },
   "fieldConfig": { "defaults": { "unit": "tasks/s" } },
   "targets": [
    {
     "expr": "sum without($group_without) (rate(daml_executor_tasks_stolen{namespace=\"$namespace\", pod=~\"$pod\", container=\"$container\", name=~\"$name\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Task Queuing Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 132 },
   "fieldConfig": { "defaults": { "unit": "tasks/s" } },
   "targets": [
    {
     "expr": "sum without($group_without) (rate(daml_executor_tasks_executing_queued{namespace=\"$namespace\", pod=~\"$pod\", container=\"$container\", name=~\"$name\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queued Tasks",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 141 },
   "fieldConfig": { "defaults": { "unit": " tasks" } },
   "targets": [
    {
     "expr": "daml_executor_tasks_executing_queued{namespace=\"$namespace\", pod=~\"$pod\", container=\"$container\", name=~\"$name\"}",
     "legendFormat": "Queued total - {{pod}} -- {{name}}"
    }
   ]
  }
 ]
}
{
 "title": "JVM Metrics",
 "tags": [ "jvm" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(jvm_cpu_count,namespace)"
    }
   },
   {
    "name": "app",
    "label": "App",
    "query": {
     "query": "label_values(jvm_cpu_count{namespace=~\"$namespace\"},service)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(jvm_cpu_count{namespace=~\"$namespace\", service=~\"$app\"},pod)"
    }
   },
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "label_values(jvm_cpu_count{namespace=~\"$namespace\", service=~\"$app\"},container)"
    }
   }
  ]
 },
 "panels": [
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Count",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_cpu_count{namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", service=~\"$app\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 18, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "jvm_cpu_recent_utilization_ratio{namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", service=~\"$app\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(container, pod) (rate(jvm_cpu_time_seconds_total{namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", service=~\"$app\"}[$__rate_interval]))",
     "legendFormat": "{{pod}} {{container}}"
    }
   ]
  },
  { "title": "Threads", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "jvm_thread_count{namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", service=~\"$app\"}",
     "legendFormat": "{{job}} - daemon {{jvm_thread_daemon}} - {{jvm_thread_state}}"
    }
   ]
  },
  { "title": "Garbage Collection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "GC Runs",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "sum by(gc, container, pod, jvm_gc_name, jvm_gc_action, namespace) (histogram_count(rate(jvm_gc_duration_seconds{namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", service=~\"$app\"}[$__rate_interval])))",
     "legendFormat": "{{namespace}} {{jvm_gc_name}} {{jvm_gc_action}} {{pod}} {{container}}"
    }
   ]
  },
  {
   "title": "GC Timing",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(jvm_gc_action, jvm_gc_name, container, pod, namespace) (histogram_sum(rate(jvm_gc_duration_seconds{namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", service=~\"$app\"}[$__rate_interval])))",
     "legendFormat": "rate {{namespace}} {{jvm_gc_name}} {{jvm_gc_action}} {{pod}} {{container}}"
    },
    {
     "expr": "sum by(jvm_gc_action, jvm_gc_name, container, pod, namespace) (histogram_avg(rate(jvm_gc_duration_seconds{namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", service=~\"$app\"}[$__rate_interval])))",
     "legendFormat": "avg {{namespace}} {{jvm_gc_name}} {{jvm_gc_action}} {{pod}} {{container}}"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", service=~\"$app\"}",
     "legendFormat": "{{pod}} {{container}} - {{jvm_memory_pool_name}} - {{jvm_memory_type}}"
    }
   ]
  },
  {
   "title": "Memory Limit",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_limit_bytes{namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", service=~\"$app\"}",
     "legendFormat": "{{pod}} {{container}} - {{jvm_memory_pool_name}} - {{jvm_memory_type}}"
    }
   ]
  },
  {
   "title": "Memory Used After Last GC ",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_after_last_gc_bytes{namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", service=~\"$app\"}",
     "legendFormat": "{{pod}} {{container}} - {{jvm_memory_pool_name}} - {{jvm_memory_type}}"
    }
   ]
  },
  {
   "title": "Memory Committed ",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_committed_bytes{namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", service=~\"$app\"}",
     "legendFormat": "{{pod}} {{container}} - {{jvm_memory_pool_name}} - {{jvm_memory_type}}"
    }
   ]
  },
  {
   "title": "Buffer Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_buffer_memory_used_bytes{namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", service=~\"$app\"}",
     "legendFormat": "{{pod}} {{container}} - {{jvm_buffer_pool_name}}"
    }
   ]
  },
  {
   "title": "Buffer Memory Limit",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_buffer_memory_limit_bytes{namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", service=~\"$app\"}",
     "legendFormat": "{{pod}} {{container}} - {{jvm_buffer_pool_name}}"
    }
   ]
  }
 ]
}