{
 "title": "BFT ordering",
 "tags": [ "bft-sequencers" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(daml_health_status,namespace)"
    }
   },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(daml_health_status{namespace=~\"$namespace\"},job)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(daml_health_status{namespace=~\"$namespace\", job=~\"$job\"},node)"
    }
   },
   {
    "name": "percentile",
    "label": "Percentile",
    "query": ".5,.6,.7,.75,.8,.9,.95,.99,.999"
   }
  ]
 },
 "panels": [
  {
   "title": "Global overview (instance view)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Current Epoch",
   "type": "stat",
   "description": "ISS proceeds in epochs with stable leader assignments to \"segments\" and stable topology (i.e., sequencers can be added and remove only at epoch boundaries and leaders are reassigned to segments also at epoch boundaries). This is the current epoch.",
   "gridPos": { "h": 11, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "daml_sequencer_bftordering_consensus_epoch{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\"}",
     "legendFormat": "{{namespace}}.{{node}}"
    }
   ]
  },
  {
   "title": "Epoch Length",
   "type": "stat",
   "description": "Size in blocks of the current epoch.",
   "gridPos": { "h": 11, "w": 3, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "daml_sequencer_bftordering_consensus_epoch_length{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\"}",
     "legendFormat": "{{namespace}}.{{node}}"
    }
   ]
  },
  {
   "title": "Validators",
   "type": "stat",
   "description": "Number of active validators",
   "gridPos": { "h": 11, "w": 3, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "daml_sequencer_bftordering_topology_validators{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\"}",
     "legendFormat": "{{namespace}}.{{node}}"
    }
   ]
  },
  {
   "title": "Peers count",
   "type": "stat",
   "description": "Number of connected and authenticated P2P peers for the selected sequencer. It should be > 2/3 at all times.",
   "gridPos": { "h": 11, "w": 13, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "daml_sequencer_bftordering_p2p_connections_connected{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\"}",
     "legendFormat": "Connected ({{namespace}}.{{node}})"
    },
    {
     "expr": "daml_sequencer_bftordering_p2p_connections_authenticated{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\"}",
     "legendFormat": "Authenticated ({{namespace}}.{{node}})"
    }
   ]
  },
  {
   "title": "Max tolerated faults",
   "type": "stat",
   "gridPos": { "h": 12, "w": 3, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "daml_sequencer_bftordering_topology_max_tolerated_faults{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\"}",
     "legendFormat": "{{namespace}}.{{node}}"
    }
   ]
  },
  {
   "title": "Weak quorum",
   "type": "stat",
   "description": "The size of a weak quorum or non-faulty nodes, needed e.g. to disseminate batches",
   "gridPos": { "h": 12, "w": 3, "x": 3, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "daml_sequencer_bftordering_topology_weak_quorum{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\"}",
     "legendFormat": "{{namespace}}.{{node}}"
    }
   ]
  },
  {
   "title": "Strong quorum",
   "type": "stat",
   "description": "The size of a strong quorum, needed for ordering consensus",
   "gridPos": { "h": 12, "w": 3, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "daml_sequencer_bftordering_topology_strong_quorum{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\"}",
     "legendFormat": "{{namespace}}.{{node}}"
    }
   ]
  },
  {
   "title": "Total Output Blocks",
   "type": "stat",
   "description": "Latest block number ordered and available for the read path. When there is no traffic, a block can be empty.",
   "gridPos": { "h": 12, "w": 7, "x": 9, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(namespace, job, node) (daml_sequencer_bftordering_global_ordered_blocks_total{namespace=~\"$namespace\", job=~\"$job\", node=~\"$node\"})",
     "legendFormat": "{{namespace}}.{{node}}"
    }
   ]
  },
  {
   "title": "Total Output Requests",
   "type": "stat",
   "description": "Total number of requests ordered and output to the read path.",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (namespace,job,node) (histogram_sum(daml_sequencer_bftordering_output_block_size_requests{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\"}))",
     "legendFormat": "{{namespace}}.{{node}}"
    }
   ]
  },
  {
   "title": "BFT ordering members",
   "type": "timeseries",
   "description": "Sequencers that are part of the BFT ordering topology",
   "gridPos": { "h": 21, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "daml_sequencer_bftordering_topology_topology_member{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\"}",
     "legendFormat": " (reporter: {{namespace}}.{{node}}) {{sequencer_id}}"
    }
   ]
  },
  {
   "title": "BFT ordering leaders",
   "type": "timeseries",
   "description": "Sequencers that are allowed to propose blocks for ordering",
   "gridPos": { "h": 21, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "daml_sequencer_bftordering_topology_topology_leader{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\"}",
     "legendFormat": " (reporter: {{namespace}}.{{node}}) {{sequencer_id}}"
    }
   ]
  },
  {
   "title": "P2P authenticated endpoints",
   "type": "timeseries",
   "gridPos": { "h": 21, "w": 8, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "daml_sequencer_bftordering_p2p_authenticated_endpoint{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\"}",
     "legendFormat": "(reporter: {{namespace}}.{{node}}) {{endpoint}}"
    }
   ]
  },
  {
   "title": "P2P connected but unauthenticated endpoints",
   "type": "timeseries",
   "gridPos": { "h": 21, "w": 8, "x": 8, "y": 45 },
   "targets": [
    {
     "expr": "daml_sequencer_bftordering_p2p_unauthenticated_endpoint{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\"}",
     "legendFormat": "(reporter: {{namespace}}.{{node}}) {{endpoint}}"
    }
   ]
  },
  {
   "title": "P2P disconnected endpoints",
   "type": "timeseries",
   "gridPos": { "h": 21, "w": 8, "x": 16, "y": 45 },
   "targets": [
    {
     "expr": "daml_sequencer_bftordering_p2p_disconnected_endpoint{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\"}",
     "legendFormat": "(reporter: {{namespace}}.{{node}}) {{endpoint}}"
    }
   ]
  },
  {
   "title": "Requests end-to-end ordering latency",
   "type": "timeseries",
   "description": "Wall-clock duration between the instant a request is received by the CantonBFT orderer and the instant the fully assembled ordered block metadata is stored, just before the request is pushed to the post-ordering stages. Its meaningfulness requires wall-clock synchronization, as not all ordered requests are received and timestamped on this node.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($percentile, sum by (namespace, job, node) (rate(daml_sequencer_bftordering_global_requests_ordering_latency_duration_seconds{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\"}[$__rate_interval])))",
     "legendFormat": "{{namespace}}.{{node}}"
    }
   ]
  },
  {
   "title": "Throughput - requests/s",
   "type": "timeseries",
   "description": "Rate of requests ordered and output to the read path.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by (namespace, job, node) (irate(daml_sequencer_bftordering_global_ordered_requests_total{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "{{namespace}}.{{node}}"
    }
   ]
  },
  {
   "title": "Requests / Block",
   "type": "timeseries",
   "description": "Number of requests per consensus block.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "histogram_sum(sum by(namespace, job, node, mode) (rate(daml_sequencer_bftordering_output_block_size_requests{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\"}[$__rate_interval]))) / histogram_count(sum by(namespace, job, node, mode) (rate(daml_sequencer_bftordering_output_block_size_requests{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\"}[$__rate_interval])))",
     "legendFormat": "{{namespace}}.{{node}} ({{mode}})"
    }
   ]
  },
  {
   "title": "Throughput - blocks/s",
   "type": "timeseries",
   "description": "Rate of blocks ordered and output to the read path.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by (namespace, job, node, is_block_empty) (irate(daml_sequencer_bftordering_global_ordered_blocks_total{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "{{namespace}}.{{node}} (empty: {{is_block_empty}})"
    }
   ]
  },
  {
   "title": "Batches (PoAs) / Block",
   "type": "timeseries",
   "description": "Number of batches (proofs of availability) per consensus block. Note that < 1 average batch per block likely means empty blocks are being created.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "histogram_sum(sum by(namespace, job, node, mode) (rate(daml_sequencer_bftordering_output_block_size_batches{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\"}[$__rate_interval]))) / histogram_count(sum by(namespace, job, node, mode) (rate(daml_sequencer_bftordering_output_block_size_batches{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\"}[$__rate_interval])))",
     "legendFormat": "{{namespace}}.{{node}} ({{mode}})"
    }
   ]
  },
  {
   "title": "Throughput - batches/s",
   "type": "timeseries",
   "description": "Rate of batches (proofs of availability) ordered and output to the read path.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "irate(daml_sequencer_bftordering_global_ordered_batches_total{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\"}[$__rate_interval])",
     "legendFormat": "{{namespace}}.{{node}}"
    }
   ]
  },
  {
   "title": "Sequencer core backpressure delay (ms)",
   "type": "timeseries",
   "description": "Delay introduced by the sequencer core being too slow consuming blocks from ordering, in milliseconds",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "daml_sequencer_bftordering_sequencer_core_backpressure_current_delay_millis{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\"}",
     "legendFormat": "{{namespace}}.{{node}}"
    }
   ]
  },
  {
   "title": "Sequencer core buffer size (blocks #)",
   "type": "timeseries",
   "description": "Size of the buffer in the subscription from the orderer to the sequencer core, in blocks",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "daml_sequencer_bftordering_sequencer_core_subscription_buffer_size{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\"}\n",
     "legendFormat": "{{namespace}}.{{node}}}"
    }
   ]
  },
  {
   "title": "Blacklisted Sequencers",
   "type": "timeseries",
   "description": "How many epochs a sequencer is blacklisted",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 94 },
   "targets": [
    {
     "expr": "daml_sequencer_bftordering_blacklist_sequencer{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\"}",
     "legendFormat": "(reporter: {{namespace}}.{{node}}) {{blacklist_sequencer}}"
    }
   ]
  },
  {
   "title": "Stream Buffer Metrics",
   "type": "timeseries",
   "description": "Size of the stream buffer at various stages",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "daml_sequencer_block_stream_buffer_size{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\"}",
     "legendFormat": "{{namespace}}.{{node}}.{{element}}"
    }
   ]
  },
  {
   "title": "Block delay",
   "type": "timeseries",
   "description": "Wall-clock time of the ordered block being provided to the sequencer minus BFT time of the block",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($percentile, sum by(namespace, job, node, mode) (rate(daml_sequencer_bftordering_output_block_delay_duration_seconds{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\"}[$__rate_interval])))",
     "legendFormat": "{{namespace}}.{{node}}"
    }
   ]
  },
  {
   "title": "Output Block Payload Size",
   "type": "timeseries",
   "description": "Size of the payloads of blocks ordered and output to the read path.",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "histogram_quantile($percentile, sum by(namespace, job, node, mode) (rate(daml_sequencer_bftordering_output_block_size_bytes{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\"}[$__rate_interval])))",
     "legendFormat": "{{namespace}}.{{node}}.{{mode}}"
    }
   ]
  },
  {
   "title": "PBFT Voting Power %",
   "type": "state-timeline",
   "description": "Percentage of votes received by the currently selected sequencer at every major PBFT stage. Should be > 2/3 at all times, else a leader change (\"view change\" in PBFT parlance) occurs automatically.",
   "gridPos": { "h": 28, "w": 24, "x": 0, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "daml_sequencer_bftordering_consensus_prepare_votes_percent{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\"}",
     "legendFormat": "(reporter: {{namespace}}.{{node}}) Prepare {{voting_sequencer}}"
    },
    {
     "expr": "daml_sequencer_bftordering_consensus_commit_votes_percent{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\"}",
     "legendFormat": "(reporter: {{namespace}}.{{node}}) Commit {{voting_sequencer}}"
    }
   ]
  },
  {
   "title": "Non-compliant behaviors",
   "type": "timeseries",
   "description": "Count of non-compliant and possibly byzantine protocol behaviors detected by the currently selected sequencer.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 129 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (namespace, job, node) (irate(daml_sequencer_bftordering_security_noncompliant_behavior_total{namespace=~\"$namespace\", job=~\"$job\", node=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "{{namespace}}.{{node}}"
    }
   ]
  },
  {
   "title": "Mempool Size (requests)",
   "type": "timeseries",
   "description": "Size of the incoming requests buffer (\"mempool\") for the selected sequencer. Its maximum size in bytes and requests count can be currently set via static configuration.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 129 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "daml_sequencer_bftordering_ingress_requests_queued{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\"}",
     "legendFormat": "{{namespace}}.{{node}}"
    }
   ]
  },
  {
   "title": "Block proposals requested by consensus",
   "type": "timeseries",
   "description": "Number of proposals requested by consensus.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 136 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "daml_sequencer_bftordering_availability_requested_proposals{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\"}",
     "legendFormat": "{{namespace}}.{{node}}"
    }
   ]
  },
  {
   "title": "Block proposals requested by consensus (batches)",
   "type": "timeseries",
   "description": "Number of batches requested to be proposed in consensus.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 136 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "daml_sequencer_bftordering_availability_requested_batches{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\"}",
     "legendFormat": "{{namespace}}.{{node}}"
    }
   ]
  },
  {
   "title": "Batches being disseminated",
   "type": "timeseries",
   "description": "Number of batches that are being disseminated.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 143 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "daml_sequencer_bftordering_availability_disseminating_batches{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\",ready_for_consensus=~\"false|true\"}",
     "legendFormat": "{{namespace}}.{{node}}"
    }
   ]
  },
  {
   "title": "Outstanding batch requests",
   "type": "timeseries",
   "description": "Number of batches requested by the availability module and not yet provided.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 143 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "daml_sequencer_bftordering_mempool_requested_batches{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\"}",
     "legendFormat": "{{namespace}}.{{node}}"
    }
   ]
  },
  {
   "title": "Sequencer overview: $reporting_sequencer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 150 },
   "repeat": "instance",
   "targets": [
    {}
   ]
  },
  {
   "title": "Requests being disseminated",
   "type": "timeseries",
   "description": "Number of requests in batches that are being disseminated.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 151 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "daml_sequencer_bftordering_availability_disseminating_requests{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\",ready_for_consensus=~\"false|true\"}",
     "legendFormat": "{{namespace}}.{{node}}"
    }
   ]
  },
  {
   "title": "Total Network Input",
   "type": "timeseries",
   "description": "Total network ingress for the currently selected sequencer split by sender.",
   "gridPos": { "h": 14, "w": 6, "x": 12, "y": 151 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(namespace, job, node, source_sequencer) (daml_sequencer_bftordering_p2p_receive_received_bytes_total{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\"})",
     "legendFormat": "(reporter: {{namespace}}.{{node}}) {{source_sequencer}}"
    }
   ]
  },
  {
   "title": "Total Network Output",
   "type": "timeseries",
   "description": "Total network egress for the currently selected sequencer split by destination.",
   "gridPos": { "h": 14, "w": 6, "x": 18, "y": 151 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(namespace, job, node, target_sequencer) (daml_sequencer_bftordering_p2p_send_sent_bytes_total{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\"})",
     "legendFormat": "(reporter: {{namespace}}.{{node}}) {{target_sequencer}}"
    }
   ]
  },
  {
   "title": "Bytes being disseminated",
   "type": "timeseries",
   "description": "Number of payload bytes in requests within batches that are being disseminated.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 158 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "daml_sequencer_bftordering_availability_disseminating_bytes{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\",ready_for_consensus=~\"false|true\"}",
     "legendFormat": "{{namespace}}.{{node}}"
    }
   ]
  }
 ]
}