{
 "title": "Traffic-based app rewards (CIP-104)",
 "description": "Traffic based app rewards (CIP-104)",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(splice_calculate_rewards_v2_processing_delay_duration_seconds,namespace)"
    }
   },
   {
    "name": "dryRun",
    "query": {
     "query": "label_values(splice_calculate_rewards_v2_processing_delay_duration_seconds,dryRun)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CalculateRewardsV2 contracts",
   "type": "timeseries",
   "description": "Number of active CalculateRewardsV2 contracts, as seen by the sv app.\n\nOne such contract should be created when a round is closed, and should be archived as soon as SVs finish voting on the root hash of the reward merkle tree (usually within a minute).",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "max by (namespace,dryRun)((splice_calculate_rewards_v2_active_contracts{namespace=~\"$namespace\", dryRun=~\"$dryRun\"} != -1))",
     "legendFormat": "{{namespace}} {{dryRun}}"
    }
   ]
  },
  {
   "title": "ProcessRewardsV2 contracts",
   "type": "timeseries",
   "description": "Number of active ProcessRewardsV2 contracts, as seen by the sv app.\n\nA few such contract should be created when the SVs finish voting on the root hash of the reward merkle tree, and they should be archived as the SVs create the corresponding minting allowances. Within a few minutes, there should be no ProcessRewardsV2 contracts left.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "max by (namespace, dryRun)(splice_process_rewards_v2_active_contracts{namespace=~\"$namespace\", dryRun=\"$dryRun\"} != -1)",
     "legendFormat": "{{namespace}} {{dryRun}}"
    }
   ]
  },
  {
   "title": "RewardCouponV2 contracts, average across all SVs, by contract age",
   "type": "timeseries",
   "description": "Stacked time series for the number of active RewardCouponV2 contracts, as seen by the sv app. Data is averages across all selected SVs, and disaggregated by contract age into 4 hardcoded buckets.\n\nRewardCouponV2 contracts have a TTL of 36h by default, validators may decide to wait a few rounds in order to batch the minting of reward coupons.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "avg by (bucket, ageLowerBound, ageUpperBound)(splice_reward_coupon_v2_active_contracts{namespace=~\"$namespace\"} != -1)",
     "legendFormat": "{{ageLowerBound}} - {{ageUpperBound}}"
    }
   ]
  },
  {
   "title": "Parties with hidden coupons",
   "type": "table",
   "description": "Leaderboard of parties with hidden reward coupons.\n\nHidden coupons are created when a party is due rewards, but has not vetted the required package. The reward coupons are created without the party as observer in that case. As soon as the party vets the required package, the party is added as observer.\n\nIf you ever see any parties here, tell their validator node to upgrade or fix their package vetting.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "max by (namespace)(splice_scan_reward_computation_reward_coupons_v2_hidden_coupons{namespace=~\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ingest verdicts and activity records (ScanVerdictIngestionService in scan app)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 }
  },
  {
   "title": "Latency: last ingested verdict lag",
   "type": "timeseries",
   "description": "The time difference between the last ingested verdict record time and the current wall clock time.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(timestamp(splice_scan_verdict_ingestion_last_record_time_us{namespace=~\"$namespace\"}) - (splice_scan_verdict_ingestion_last_record_time_us{namespace=~\"$namespace\"} > 0) / 1e6)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Traffic: verdicts ingestion rate",
   "type": "timeseries",
   "description": "Rate of ingestion of mediator verdicts per second",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "targets": [
    {
     "expr": "rate(splice_scan_verdict_ingestion_count_total{namespace=~\"$namespace\"}[$__rate_interval])",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Saturation: verdict batch size (10min running average)",
   "type": "timeseries",
   "description": "Average and 99th quantile batch size.\n\nVerdicts are streamed in from the mediator, then batched in the scan app. For each batch we do one lookup for traffic summaries in the sequencer, and submit one SQL transaction to store all app activity data.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "targets": [
    {
     "expr": "(histogram_sum(sum by(namespace)(rate(splice_scan_verdict_ingestion_batch_size[10m])))\n/\nhistogram_count(sum by(namespace)(rate(splice_scan_verdict_ingestion_batch_size[10m]))))",
     "legendFormat": "{{namespace}} avg"
    }
   ]
  },
  {
   "title": "Calculate reward merkle tree (RewardComputationTrigger in scan app)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 }
  },
  {
   "title": "Latency: median trigger task duration",
   "type": "timeseries",
   "description": "The time it took to complete a task",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, rate(splice_trigger_latency_duration_seconds{namespace=~\"$namespace\", trigger_name=\"RewardComputationTrigger\", trigger_type=\"taskbased\"}[$__rate_interval]))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Traffic: Trigger runs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 27 },
   "targets": [
    {
     "expr": "rate(splice_trigger_completed_total{trigger_name=~\"RewardComputationTrigger\",outcome=~\"success|failure\", namespace=~\"$namespace\"}[$__rate_interval])",
     "legendFormat": "{{namespace}} {{outcome}}"
    }
   ]
  },
  {
   "title": "Errors: Failed trigger attempts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 27 },
   "targets": [
    {
     "expr": "sum by(errorCodeId, namespace, node_type, trigger_name) (rate(splice_trigger_attempted_total{namespace=~\"$namespace\", trigger_name=~\"RewardComputationTrigger\", statusCode!~\"OK\"}[$__rate_interval])) > 0",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Latency: DbScanRewardsReferenceStore lag",
   "type": "timeseries",
   "description": "The time difference between the last ingested record time and the current wallclock time.\n\nNote that the last ingested record time metric only updates when the store ingests a new transaction so if there is no activity, the last ingested record time will not advance.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(timestamp(splice_store_last_ingested_record_time_ms{namespace=~\"$namespace\",store_name=~\"DbScanRewardsReferenceStore\"}) - (splice_store_last_ingested_record_time_ms{namespace=~\"$namespace\",store_name=~\"DbScanRewardsReferenceStore\"} > 0) / 1e3)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Batches",
   "type": "stat",
   "description": "Number of batches in the latest computed round. Median value from all selected scan apps.",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "median" ] } },
   "targets": [
    {
     "expr": "quantile(0.5,splice_scan_reward_computation_batches_created_count{namespace=~\"$namespace\"})",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Activity records",
   "type": "stat",
   "description": "Number of activity records in the latest computed round. Median value from all selected scan apps.",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "quantile(0.5, splice_scan_reward_computation_activity_records_count{namespace=~\"$namespace\"})",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Active parties",
   "type": "stat",
   "description": "Number of parties with activity in the latest computed round. Median value from all selected scan apps",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "quantile(0.5, splice_scan_reward_computation_active_parties_count{namespace=~\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rewarded parties",
   "type": "stat",
   "description": "Number of parties with rewards in the latest computed round. Median value from all selected scan apps.",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "quantile(0.5, splice_scan_reward_computation_rewarded_parties_count{namespace=~\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Voting on root hash (CalculateRewardsTrigger in sv app)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 }
  },
  {
   "title": "Latency: median trigger task duration",
   "type": "timeseries",
   "description": "The time it took to complete a task",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, rate(splice_trigger_latency_duration_seconds{namespace=~\"$namespace\", trigger_name=~\"CalculateRewards.*Trigger\", dryRun=~\"$dryRun\", trigger_type=\"taskbased\"}[$__rate_interval]))",
     "legendFormat": "{{namespace}} {{dryRun}}"
    }
   ]
  },
  {
   "title": "Latency: DbSvDsoStore lag",
   "type": "timeseries",
   "description": "The time difference between the last ingested record time and the current wallclock time.\n\nNote that the last ingested record time metric only updates when the store ingests a new transaction so if there is no activity, the last ingested record time will not advance. For a party performing reward collection, e.g., the validator operator party you expect at least one transaction every round so the lag should not go above 20min.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(timestamp(splice_store_last_ingested_record_time_ms{namespace=~\"$namespace\",store_name=~\"DbSvDsoStore\"}) - (splice_store_last_ingested_record_time_ms{namespace=~\"$namespace\",store_name=~\"DbSvDsoStore\"} > 0) / 1e3)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Latency: time between round end and confirming root hash",
   "type": "timeseries",
   "description": "the time it took between the closing of a round, and this SV's confirmation for the CalculateRewardsV2 contract's processing",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_avg(rate(splice_calculate_rewards_v2_processing_delay_duration_seconds{namespace=~\"$namespace\", dryRun=~\"$dryRun\"}[$__rate_interval]))",
     "legendFormat": "{{namespace}} {{dryRun}}"
    }
   ]
  },
  {
   "title": "Traffic: trigger runs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "rate(splice_trigger_completed_total{trigger_name=~\"ProcessRewardsTrigger.*\", dryRun=\"$dryRun\", outcome=~\"success|failure\", namespace=~\"$namespace\"}[$__rate_interval])",
     "legendFormat": "{{namespace}} {{dryRun}} {{outcome}}"
    }
   ]
  },
  {
   "title": "Errors: Failed trigger attempts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 52 },
   "targets": [
    {
     "expr": "sum by(statusCode, namespace, node_type, trigger_name) (rate(splice_trigger_attempted_total{namespace=~\"$namespace\", trigger_name=~\"CalculateRewards.*Trigger\", dryRun=\"$dryRun\", statusCode!~\"OK\"}[$__rate_interval]))",
     "legendFormat": "{{namespace}} {{dryRun}} {{statusCode}}"
    }
   ]
  },
  {
   "title": "Rate of reading root hash from other scans",
   "type": "timeseries",
   "description": "Rate of BFT reads of the root hash. BFT reads happens if this SV node started ingesting verdicts after the round on which is being voted.\n\nI.e., BFT reads should only happen after the SV node was onboarded or after its verdict store data was reset.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(splice_calculate_rewards_v2_root_hash_bft_reads{namespace=~\"$namespace\", dryRun=~\"$dryRun\"}[$__rate_interval])",
     "legendFormat": "{{namespace}} {{dryRun}}"
    }
   ]
  },
  {
   "title": "Creating minting allowances (ProcessRewardsTrigger in sv app)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 }
  },
  {
   "title": "Latency: median trigger task duration",
   "type": "timeseries",
   "description": "The time it took to complete a task",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, rate(splice_trigger_latency_duration_seconds{namespace=~\"$namespace\", trigger_name=~\"ProcessRewards.*Trigger\", dryRun=~\"$dryRun\", trigger_type=\"taskbased\"}[$__rate_interval]))",
     "legendFormat": "{{namespace}} {{dryRun}}"
    }
   ]
  },
  {
   "title": "Latency: DbSvDsoStore lag",
   "type": "timeseries",
   "description": "The time difference between the last ingested record time and the current wallclock time.\n\nNote that the last ingested record time metric only updates when the store ingests a new transaction so if there is no activity, the last ingested record time will not advance. For a party performing reward collection, e.g., the validator operator party you expect at least one transaction every round so the lag should not go above 20min.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(timestamp(splice_store_last_ingested_record_time_ms{namespace=~\"$namespace\",store_name=~\"DbSvDsoStore\"}) - (splice_store_last_ingested_record_time_ms{namespace=~\"$namespace\",store_name=~\"DbSvDsoStore\"} > 0) / 1e3)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Latency: time between round end and processing a reward batch",
   "type": "timeseries",
   "description": "The time it took between the closing of a round, and this SV's processing of a ProcessRewardsV2 contract for that round",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_avg(rate(splice_process_rewards_v2_processing_delay_duration_seconds{namespace=~\"$namespace\", dryRun=~\"$dryRun\"}[$__rate_interval]))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Traffic: trigger runs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 69 },
   "targets": [
    {
     "expr": "rate(splice_trigger_completed_total{trigger_name=~\"ProcessRewards.*Trigger\", dryRun=~\"$dryRun\", outcome=~\"success|failure\", namespace=~\"$namespace\"}[$__rate_interval])",
     "legendFormat": "{{namespace}} {{dryRun}} {{outcome}}"
    }
   ]
  },
  {
   "title": "Errors: Failed trigger attempts",
   "type": "timeseries",
   "description": "Note: this is a delegate based trigger. It is normal that this trigger fails due to contention as multiple SVs attempt to complete the same task at the same time. Example errors:\n\n- FAILED_PRECONDITION: UNKNOWN_CONTRACT_SYNCHRONIZERS: The following contracts have been archived\n- NOT_FOUND: LOCAL_VERDICT_INACTIVE_CONTRACTS: Rejected transaction is referring to inactive contracts\n- ABORTED: LOCAL_VERDICT_LOCKED_CONTRACTS: Rejected transaction is referring to locked contracts",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 69 },
   "targets": [
    {
     "expr": "sum by(statusCode, namespace, node_type, trigger_name) (rate(splice_trigger_attempted_total{namespace=~\"$namespace\", trigger_name=~\"ProcessRewards.*Trigger\", dryRun=~\"$dryRun\", statusCode!~\"OK\"}[$__rate_interval])) > 0",
     "legendFormat": "{{namespace}} {{true}} {{statusCode}}"
    }
   ]
  },
  {
   "title": "Rate of reading reward data from other scans",
   "type": "timeseries",
   "description": "Rate of BFT reads of reward data. BFT reads happens if this SV node's RewardComputationTrigger did not (yet) calculate rewards for this round.\n\nBFT reads here mean the SV is behind on calculating rewards, but still participates in creating minting allowance contracts.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 69 },
   "targets": [
    {
     "expr": "rate(splice_process_rewards_v2_batch_bft_reads_total{namespace=~\"$namespace\", dryRun=\"$dryRun\"}[$__rate_interval])",
     "legendFormat": "{{namespace}} {{dryRun}}"
    }
   ]
  }
 ]
}