{
 "title": "Global Domain Catchup",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(daml_sequencer_client_handler_delay,namespace)"
    }
   },
   {
    "name": "migration",
    "query": {
     "query": "label_values(daml_sequencer_client_handler_delay{namespace=~\"$namespace\"},job)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Client Delay", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Sequencer Client Delay",
   "type": "timeseries",
   "description": "Delay on event processing of a sequencer, compared to the collective",
   "gridPos": { "h": 12, "w": 15, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "min by (namespace, job) (daml_sequencer_block_delay{namespace=~\"$namespace\", component=\"sequencer\",job=~\"global-domain-$migration-sequencer\"})",
     "legendFormat": "{{namespace}}-{{job}}"
    }
   ]
  },
  {
   "title": "Sequencer Catchup Speed",
   "type": "timeseries",
   "description": "Catchup speed of the sequencer in the last 5min",
   "gridPos": { "h": 12, "w": 9, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max by (namespace, job) (delta(daml_sequencer_block_delay{namespace=~\"$namespace\", component=\"sequencer\",job=~\"global-domain-$migration-sequencer\"}[5m])) / 5",
     "legendFormat": "processing time {{namespace}}-{{job}} / min"
    }
   ]
  },
  {
   "title": "Participant Client Delay",
   "type": "timeseries",
   "description": "Delay on event processing of the participant, compared to the sequencers it is connected to.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by (namespace) (timestamp(daml_sequencer_client_handler_last_sequencing_time_micros{namespace=~\"$namespace\",component=\"participant\"}) - ((daml_sequencer_client_handler_last_sequencing_time_micros{namespace=~\"$namespace\",component=\"participant\"} > 0) / 1e6))",
     "legendFormat": "{{namespace}} {{node}}"
    }
   ]
  },
  {
   "title": "Mediator Client Delay",
   "type": "timeseries",
   "description": "Delay on event processing of a mediator, compared to its corresponding sequencer",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by (namespace, job) (timestamp(daml_sequencer_client_handler_last_sequencing_time_micros{namespace=~\"$namespace\",component=\"mediator\",job=~\"global-domain-$migration-mediator\"}) - ((daml_sequencer_client_handler_last_sequencing_time_micros{namespace=~\"$namespace\",component=\"mediator\",job=~\"global-domain-$migration-mediator\"}  > 0) / 1e6)) ",
     "legendFormat": "{{namespace}}-{{job}}"
    }
   ]
  },
  { "title": "Synchronizer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "CantonBFT Block delay",
   "type": "timeseries",
   "description": "Wall-clock time of the ordered block being provided to the sequencer minus BFT time of the block",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(namespace, job, node, mode) (rate(daml_sequencer_bftordering_output_block_delay_duration_seconds{namespace=~\"$namespace\",job=~\"global-domain-$migration-sequencer\"}[$__rate_interval])))",
     "legendFormat": "{{namespace}}.{{node}}"
    }
   ]
  },
  {
   "title": "Sequencer core buffer size (blocks #)",
   "type": "timeseries",
   "description": "Size of the buffer in the subscription from the orderer to the sequencer core, in blocks",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "daml_sequencer_bftordering_sequencer_core_subscription_buffer_size{namespace=~\"$namespace\",job=~\"global-domain-$migration-sequencer\"}\n",
     "legendFormat": "{{namespace}}.{{node}}}"
    }
   ]
  },
  {
   "title": "CantonBFT - Throughput - requests/s",
   "type": "timeseries",
   "description": "Rate of requests ordered and output to the read path.",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by (namespace, job, node) (irate(daml_sequencer_bftordering_global_ordered_requests_total{namespace=~\"$namespace\",job=~\"global-domain-$migration-sequencer\"}[$__rate_interval]))",
     "legendFormat": "{{namespace}}.{{node}}"
    }
   ]
  },
  {
   "title": "Sequencer processing event Rate",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by(namespace, job) (rate(daml_sequencer_block_events_total{namespace=~\"$namespace\",job=~\"global-domain-$migration-sequencer\"}[$__rate_interval]))",
     "legendFormat": "{{namespace}} {{job}}"
    }
   ]
  },
  {
   "title": "Sequencer processing Block Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate((daml_sequencer_block_height{namespace=~\"$namespace\", job=~\"global-domain-$migration-sequencer\"} > 0)[$__rate_interval:])",
     "legendFormat": "{{namespace}} {{job}}"
    }
   ]
  },
  {
   "title": "CantonBFT - Throughput - epochs/s",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by (namespace, job, node) (rate(daml_sequencer_bftordering_consensus_epoch{namespace=~\"$namespace\",job=~\"global-domain-$migration-sequencer\"}[$__rate_interval]))",
     "legendFormat": "{{namespace}}.{{node}}"
    }
   ]
  },
  {
   "title": "Sequencer block height ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "daml_sequencer_block_height{namespace=~\"$namespace\", job=~\"global-domain-$migration-sequencer\"}",
     "legendFormat": "{{namespace}}-{{job}}"
    }
   ]
  },
  {
   "title": "CometBFT",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 },
   "collapsed": true,
   "panels": [
    {
     "title": "CometBFT Block Height",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
     "targets": [
      {
       "expr": "cometbft_consensus_latest_block_height{namespace=~\"$namespace\", job=~\"global-domain-$migration-cometbft-cometbft-rpc\"}",
       "legendFormat": "{{namespace}}-{{chain_id}}"
      }
     ]
    },
    {
     "title": "CometBFT blocks to process",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max by(namespace, migration) (label_replace(cometbft_consensus_latest_block_height{namespace=~\"$namespace\", job=~\"global-domain-$migration-cometbft-cometbft-rpc\"}, \"migration\", \"$1\", \"job\", \"global-domain-(\\\\d)-.*\")) - max by(namespace, migration) (label_replace(daml_sequencer_block_height{namespace=~\"$namespace\", job=~\"global-domain-$migration-sequencer\"}, \"migration\", \"$1\", \"job\", \"global-domain-(\\\\d)-.*\"))",
       "legendFormat": "{{namespace}}, migration={{migration}}"
      }
     ]
    },
    {
     "title": "CometBFT Block Syncing",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
     "targets": [
      {
       "expr": "cometbft_consensus_block_syncing{namespace=~\"$namespace\", job=~\"global-domain-$migration-cometbft-cometbft-rpc\"}",
       "legendFormat": "{{namespace}}-{{job}}"
      }
     ]
    },
    {
     "title": "Cometbft producing Block Rate",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 77 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "rate(cometbft_consensus_height{namespace=~\"$namespace\", job=~\"global-domain-$migration-cometbft-cometbft-rpc\"}[$__rate_interval])",
       "legendFormat": "{{namespace}}-{{job}}"
      }
     ]
    },
    {
     "title": "CometBFT blocks to process",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 83 },
     "targets": [
      {
       "expr": "max by(namespace, migration) (label_replace(cometbft_consensus_latest_block_height{namespace=~\"$namespace\", job=~\"global-domain-$migration-cometbft-cometbft-rpc\"}, \"migration\", \"$1\", \"job\", \"global-domain-(\\\\d)-.*\")) - max by(namespace, migration) (label_replace(daml_sequencer_block_height{namespace=~\"$namespace\", job=~\"global-domain-$migration-sequencer\"}, \"migration\", \"$1\", \"job\", \"global-domain-(\\\\d)-.*\"))",
       "legendFormat": "{{namespace}}, migration={{migration}}"
      }
     ]
    }
   ]
  }
 ]
}