{
 "title": "CometBFT",
 "description": "Internet of blockchains",
 "tags": [ "Blockchain" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(cometbft_consensus_height,namespace)"
    }
   },
   {
    "name": "chain_id",
    "label": "Chain ID",
    "query": "label_values(cometbft_consensus_height, chain_id)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(cometbft_consensus_height{chain_id=\"$chain_id\"},job)"
    }
   }
  ]
 },
 "panels": [
  { "title": "$chain_id overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Block Height",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_height{namespace=\"$namespace\", chain_id=\"$chain_id\", job=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Total Transactions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_total_txs{namespace=\"$namespace\", chain_id=\"$chain_id\", job=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Avg State Block Processing",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(cometbft_state_block_processing_time_sum{chain_id=\"$chain_id\", job=\"$instance\"}[$__rate_interval]) / rate(cometbft_state_block_processing_time_count{chain_id=\"$chain_id\", job=\"$instance\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Bonded Tokens",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_validators_power{namespace=\"$namespace\", chain_id=\"$chain_id\", job=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Block Height",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "cometbft_consensus_height{chain_id=\"$chain_id\", job=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Avg Block Time",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by(le,namespace,chain_id,job) (rate(cometbft_consensus_block_interval_seconds_bucket{namespace=\"$namespace\",chain_id=\"$chain_id\",job=\"$instance\"}[$__rate_interval])))",
     "legendFormat": "{{namespace}}-{{chain_id}}-0.9"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le,namespace,chain_id,job) (rate(cometbft_consensus_block_interval_seconds_bucket{namespace=\"$namespace\",chain_id=\"$chain_id\",job=\"$instance\"}[$__rate_interval])))",
     "legendFormat": "{{namespace}}-{{chain_id}}-0.99"
    },
    {
     "expr": "histogram_quantile(0.999, sum by(le,namespace,chain_id,job) (rate(cometbft_consensus_block_interval_seconds_bucket{namespace=\"$namespace\",chain_id=\"$chain_id\",job=\"$instance\"}[$__rate_interval])))",
     "legendFormat": "{{namespace}}-{{chain_id}}-0.999"
    }
   ]
  },
  {
   "title": "Validators",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "cometbft_consensus_validators{namespace=\"$namespace\", chain_id=\"$chain_id\", job=\"$instance\"}",
     "legendFormat": "Active"
    },
    {
     "expr": "cometbft_consensus_missing_validators{namespace=\"$namespace\", chain_id=\"$chain_id\", job=\"$instance\"}",
     "legendFormat": "Missing"
    },
    {
     "expr": "cometbft_consensus_byzantine_validators{namespace=\"$namespace\", chain_id=\"$chain_id\", job=\"$instance\"}",
     "legendFormat": "Byzantine"
    }
   ]
  },
  {
   "title": "Voting Power",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "cometbft_consensus_validators_power{namespace=\"$namespace\", chain_id=\"$chain_id\", job=\"$instance\"}",
     "legendFormat": "Online"
    },
    {
     "expr": "cometbft_consensus_missing_validators_power{namespace=\"$namespace\", chain_id=\"$chain_id\", job=\"$instance\"}",
     "legendFormat": "Missing"
    },
    {
     "expr": "cometbft_consensus_byzantine_validators_power{namespace=\"$namespace\", chain_id=\"$chain_id\", job=\"$instance\"}",
     "legendFormat": "Byzantine"
    }
   ]
  },
  {
   "title": "Consensus round voting power",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "cometbft_consensus_round_voting_power_percent{namespace=\"$namespace\", chain_id=\"$chain_id\", service=\"$instance\"}",
     "legendFormat": "{{vote_type}}"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "cometbft_consensus_num_txs{namespace=\"$namespace\", chain_id=\"$chain_id\", job=\"$instance\"}",
     "legendFormat": "Transactions"
    }
   ]
  },
  {
   "title": "Block Size",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "cometbft_consensus_block_size_bytes{namespace=\"$namespace\", chain_id=\"$chain_id\", job=\"$instance\"}",
     "legendFormat": "Block Size"
    }
   ]
  },
  {
   "title": "Block Rate",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(cometbft_consensus_height{namespace=\"$namespace\", chain_id=\"$chain_id\", job=\"$instance\"}[$__rate_interval])"
    }
   ]
  },
  { "title": "instance overview: $instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 }, "repeat": "instance" },
  {
   "title": "Connected Peers",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cometbft_p2p_peers{namespace=\"$namespace\", chain_id=\"$chain_id\", job=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Unconfirmed Transactions",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cometbft_mempool_size{namespace=\"$namespace\", chain_id=\"$chain_id\", job=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Failed Transactions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_mempool_failed_txs{namespace=\"$namespace\", chain_id=\"$chain_id\", job=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Recheck Times",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_mempool_recheck_times{namespace=\"$namespace\", chain_id=\"$chain_id\", job=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Unconfirmed Transactions (mempool)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "cometbft_mempool_size{namespace=\"$namespace\", chain_id=\"$chain_id\", job=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Failed Transactions (mempool)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "cometbft_mempool_failed_txs{namespace=\"$namespace\", chain_id=\"$chain_id\", job=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Total Network Input",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(cometbft_p2p_peer_receive_bytes_total{namespace=\"$namespace\", chain_id=\"$chain_id\", job=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "Total Network Output",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(cometbft_p2p_peer_send_bytes_total{namespace=\"$namespace\", chain_id=\"$chain_id\", job=\"$instance\"}[$__rate_interval]) ",
     "legendFormat": "{{peer_id}}"
    }
   ]
  }
 ]
}