{
 "title": "CometBFT Network Status",
 "description": "Health status of the CometBFT P2P Network as measured by incoming / outgoing ",
 "tags": [ "Blockchain" ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(cometbft_p2p_message_receive_bytes_total,namespace)"
    }
   },
   {
    "name": "chain_id",
    "label": "Chain ID",
    "query": {
     "query": "label_values(cometbft_p2p_message_receive_bytes_total,chain_id)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(cometbft_p2p_message_receive_bytes_total{chain_id=\"$chain_id\"},job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total Network Throughput (current)",
   "type": "gauge",
   "description": "Total peer-wise rate of bytes sent or received over all channels over the P2P network",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (peer_id) (rate(cometbft_p2p_peer_receive_bytes_total{namespace=\"$namespace\", chain_id=\"$chain_id\", job=\"$instance\"}[$__rate_interval]) / 1000) + sum by (peer_id) (rate(cometbft_p2p_peer_send_bytes_total{namespace=\"$namespace\", chain_id=\"$chain_id\", job=\"$instance\"}[$__rate_interval]) / 1000)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Incoming Network Throughput",
   "type": "timeseries",
   "description": "Peer-wise rate of bytes received over all channels over the P2P network",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (peer_id) (rate(cometbft_p2p_peer_receive_bytes_total{namespace=\"$namespace\", chain_id=\"$chain_id\", job=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "Outgoing Network Throughput",
   "type": "timeseries",
   "description": "Peer-wise rate of bytes sent over all channels over the P2P network",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (peer_id) (rate(cometbft_p2p_peer_send_bytes_total{namespace=\"$namespace\", chain_id=\"$chain_id\", job=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{peer_id}}"
    }
   ]
  }
 ]
}