{
 "title": "Global Synchronizer Utilization",
 "time": { "from": "now-90d", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(daml_mediator_approved_requests_total,namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Successful transactions/s",
   "type": "timeseries",
   "description": "Successful transactions/s as measured by the mediator",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (namespace, migration_id)(rate(daml_mediator_approved_requests_total{namespace=~\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (namespace, migration_id)(rate(daml_mediator_approved_requests_total{namespace=~\"$namespace\"}[1h]))",
     "legendFormat": "hourly"
    }
   ]
  },
  {
   "title": "Total transactions/s",
   "type": "timeseries",
   "description": "total transactions/s including rejected transactions as measured by the mediator",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (namespace, migration_id) (rate(daml_mediator_requests_total{namespace=~\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (namespace, migration_id) (rate(daml_mediator_requests_total{namespace=~\"$namespace\"}[1h]))",
     "legendFormat": "hourly"
    }
   ]
  },
  {
   "title": "Approved transactions/min + maximum over the time range",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum by (namespace, migration_id) (increase(daml_mediator_approved_requests_total{namespace=~\"$namespace\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total transactions/min + maximum over time range",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum by (namespace, migration_id) (increase(daml_mediator_requests_total{namespace=~\"$namespace\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transactions not seen by DSO (absolute)",
   "type": "timeseries",
   "description": "The absolute number of transactions on the global synchronizer that are not visible to the DSO, in a sliding window of 30 minutes.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(sum(increase(daml_mediator_approved_requests_total{namespace=~\"$namespace\"}[30m])) by (namespace) - sum(increase(splice_history_updates_transactions_total{namespace=~\"$namespace\"}[30m])) by (namespace))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transaction not seen by DSO (percentage)",
   "type": "timeseries",
   "description": "The percentage of transactions on the global synchronizer that are not visible to the DSO, in a sliding window of 30 minutes.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum(increase(daml_mediator_approved_requests_total{namespace=~\"$namespace\"}[30m])) by (namespace) - sum(increase(splice_history_updates_transactions_total{namespace=~\"$namespace\"}[30m])) by (namespace)) / (sum(increase(daml_mediator_approved_requests_total{namespace=~\"$namespace\"}[30m])) by (namespace) > sum(increase(splice_history_updates_transactions_total{namespace=~\"$namespace\"}[30m])) by (namespace) or sum(increase(splice_history_updates_transactions_total{namespace=~\"$namespace\"}[30m])) by (namespace))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed Confirmation Request Rate (excluding duplicate requests)",
   "type": "timeseries",
   "description": "Confirmation requests received by the mediator but rejected either due to timeouts or due to rejected confirmations from some participants",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - sum by (namespace, migration_id) (rate(daml_mediator_approved_requests_total{namespace=~\"sv-1\"}[30m])) / sum by (namespace, migration_id)(rate(daml_mediator_requests_total{namespace=~\"sv-1\", duplicate_reject=\"false\"}[30m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Duplicate Confirmation Requests/s",
   "type": "timeseries",
   "description": "Confirmation requests with duplicate confirmation request UUID. These get rejected by the mediator.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "expr": "sum by (namespace, migration_id)(rate(daml_mediator_requests_total{namespace=~\"sv-1\", duplicate_reject=\"true\"}[30m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Discarded confirmation requests/s",
   "type": "timeseries",
   "description": "Confirmation requests that were sequenced but never processed by the mediator (e.g. dropped due to CometBFT replays): sequenced send-confirmation-request events minus requests received by the mediator.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "sum by (namespace) (rate(daml_sequencer_block_events_total{namespace=~\"$namespace\",type=\"send-confirmation-request\"}[$__rate_interval])) - sum by (namespace) (rate(daml_mediator_requests_total{namespace=~\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Discarded confirmation requests (fraction)",
   "type": "timeseries",
   "description": "Fraction of sequenced confirmation requests that were never processed by the mediator (e.g. dropped due to CometBFT replays).",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum by (namespace) (rate(daml_sequencer_block_events_total{namespace=~\"$namespace\",type=\"send-confirmation-request\"}[10m])) - sum by (namespace) (rate(daml_mediator_requests_total{namespace=~\"$namespace\"}[10m]))) / sum by (namespace) (rate(daml_sequencer_block_events_total{namespace=~\"$namespace\",type=\"send-confirmation-request\"}[10m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}