{
 "title": "Onboarded Parties",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(splice_synchronizer_topology_num_parties,namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Parties onboarded to the global synchronizer",
   "type": "stat",
   "gridPos": { "h": 13, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "splice_synchronizer_topology_num_parties{namespace=\"$namespace\"}",
     "legendFormat": "total parties"
    }
   ]
  },
  {
   "title": "Parties onboarded to the global synchronizer",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 10, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "splice_synchronizer_topology_num_parties{namespace=\"$namespace\"}",
     "legendFormat": "total parties"
    }
   ]
  },
  {
   "title": "Parties onboarded to the global synchronizer per participant",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 10, "x": 14, "y": 0 },
   "targets": [
    {
     "expr": "splice_synchronizer_topology_num_parties_per_participant{namespace=\"$namespace\"}",
     "legendFormat": "{{participant_id}}"
    }
   ]
  },
  {
   "title": "Top hosting participants",
   "type": "table",
   "gridPos": { "h": 14, "w": 9, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "Parties" } },
   "targets": [
    {
     "expr": "splice_synchronizer_topology_num_parties_per_participant{namespace=\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Onboarded parties last 24h",
   "type": "table",
   "gridPos": { "h": 14, "w": 7, "x": 9, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "Parties" } },
   "targets": [
    {
     "expr": "sum by(participant_id) (delta(splice_synchronizer_topology_num_parties_per_participant{namespace=\"$namespace\"}[24h])) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Onboarded parties in selected time range",
   "type": "table",
   "gridPos": { "h": 14, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "Parties" } },
   "targets": [
    {
     "expr": "sum by(participant_id) (delta(splice_synchronizer_topology_num_parties_per_participant{namespace=\"$namespace\"}[$__range])) > 0",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}