{
 "title": "Submission Request Amplifications",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(daml_sequencer_client_submissions_attempt_sync_errors_total,namespace)"
    }
   },
   {
    "name": "container",
    "query": {
     "query": "label_values(daml_sequencer_client_submissions_attempt_sync_errors_total,container)"
    }
   },
   {
    "name": "error",
    "query": {
     "query": "label_values(daml_sequencer_client_submissions_attempt_sync_errors_total,error)"
    }
   },
   { "name": "quantile", "query": "0.9, 0.95, 0.99" },
   {
    "name": "sequencerAlias",
    "query": {
     "query": "label_values(daml_sequencer_client_submissions_attempt_sync_errors_total,sequencerAlias)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Sequencer submission with synchronous errors",
   "type": "timeseries",
   "description": "Count of send request attempts which receive a synchronous error",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (error, namespace, container, sequencerAlias) (\n  rate(daml_sequencer_client_submissions_attempt_sync_errors_total{namespace=~\"$namespace\", container=~\"$container\", error=~\"$error\", sequencerAlias=~\"$sequencerAlias\"}[$__rate_interval])\n)",
     "legendFormat": "{{namespace}} - {{sequencerAlias}} - {{container}} - {{error}}"
    }
   ]
  },
  {
   "title": "Amplified submissions",
   "type": "timeseries",
   "description": "Count of send request attempts which are amplified",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum by (namespace, container, sequencerAlias) (\n  rate(daml_sequencer_client_submissions_amplified_attempts_total{namespace=~\"$namespace\", container=~\"$container\", sequencerAlias=~\"$sequencerAlias\"}[$__rate_interval])\n)",
     "legendFormat": "{{namespace}} - {{sequencerAlias}} - {{container}}"
    }
   ]
  },
  {
   "title": "Skipped attempts because of no connection available",
   "type": "timeseries",
   "description": "Count of send attempts which are skipped because no connection is available",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "sum by(namespace, container) (rate(daml_sequencer_client_submissions_no_connection_available_total{namespace=~\"$namespace\", container=~\"$container\"}[$__rate_interval]))",
     "legendFormat": "{{namespace}} - {{container}}"
    }
   ]
  },
  {
   "title": "Amplification",
   "type": "timeseries",
   "description": "Rate and timings of submission request attempts to a sequencer",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  $quantile, \n  sum by(le) (\n    rate(daml_sequencer_client_submissions_amplification_duration_seconds{namespace=~\"$namespace\", sequencerAlias=~\"$sequencerAlias\"}[$__rate_interval])\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Percentage of amplified submissions over total submissions",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expression": "$B/$A", "type": "math" }
   ]
  },
  {
   "title": "Amplification request attempts (last 24h)",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "sum by(sequencerAlias) (\n  increase(daml_sequencer_client_submissions_amplified_attempts_total{sequencerAlias=~\"$sequencerAlias\"}[24h])\n)",
     "legendFormat": "{{sequencerAlias}}"
    }
   ]
  }
 ]
}