{
 "title": "SV Status Reports",
 "description": "Show the DSO health based on the SV status reports.",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(splice_sv_status_report_creation_time_us,namespace)"
    }
   },
   {
    "name": "sv_party",
    "label": "report publisher",
    "query": {
     "query": "label_values(splice_sv_status_report_creation_time_us,report_publisher)"
    }
   },
   {
    "name": "version",
    "query": {
     "query": "label_values(splice_sv_status_report_creation_time_us,canton_version)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Report Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status Report Creation Time Lag (current)",
   "type": "gauge",
   "description": "Difference between the current time, and the creation time of the last status report (as ingested by any of the selected namespaces)",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - max by(report_publisher) (splice_sv_status_report_creation_time_us) / 1000000",
     "legendFormat": "{{report_publisher}}"
    }
   ]
  },
  {
   "title": "Report Creation Time Lag",
   "type": "timeseries",
   "description": "Difference between the current time and the maximum report creation time, as ingested by any of the selected namespaces",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "time() - max by (report_publisher) (splice_sv_status_report_creation_time_us{namespace=~\"$namespace\", report_publisher=~\"$sv_party\", canton_version=~\"$version\"}) / 1000000",
     "legendFormat": "{{report_publisher}}"
    }
   ]
  },
  {
   "title": "Reporting Frequency (current)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "recpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(max by(report_publisher) (splice_sv_status_report_number{namespace=~\"$namespace\", report_publisher=~\"$sv_party\", canton_version=~\"$version\"})[5m:30s]) * 60",
     "legendFormat": "{{report_publisher}}"
    }
   ]
  },
  {
   "title": "Reporting Frequency",
   "type": "timeseries",
   "description": "First, takes the maximum report number for each SV node (as seen by ANY of the selected namespaces).\n\nThen, takes the 5m rate of change in that metric.",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "recpm" } },
   "targets": [
    {
     "expr": "rate(max by(report_publisher) (splice_sv_status_report_number{namespace=~\"$namespace\", report_publisher=~\"$sv_party\", canton_version=~\"$version\"})[5m:30s]) * 60",
     "legendFormat": "{{report_publisher}}"
    }
   ]
  },
  {
   "title": "Additional Info: Report time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "Report Creation Time",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
     "targets": [
      {
       "expr": "max by (namespace, report_publisher) (splice_sv_status_report_creation_time_us{namespace=~\"$namespace\", report_publisher=~\"$sv_party\", canton_version=~\"$version\"}) / 1000",
       "legendFormat": "{{report_publisher}} @ {{namespace}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Additional Info: CometBFT",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "CometBFT Height",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 81 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "max by (namespace, report_publisher) (splice_sv_status_report_cometbft_height{namespace=~\"$namespace\", report_publisher=~\"$sv_party\", canton_version=~\"$version\"})",
       "legendFormat": "{{report_publisher}} @ {{namespace}}"
      }
     ]
    },
    {
     "title": "CometBFT Height Lag",
     "type": "timeseries",
     "description": "Maximal minus minimal CometBFT height reported by the SV status reports seen from one SV's perspective",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 89 },
     "targets": [
      {
       "expr": "max by (namespace) (max by (report_publisher, namespace) (splice_sv_status_report_cometbft_height{namespace=~\"$namespace\", report_publisher=~\"$sv_party\", canton_version=~\"$version\"}) ) - min by (namespace) (max by (report_publisher, namespace) (splice_sv_status_report_cometbft_height{namespace=~\"$namespace\", report_publisher=~\"$sv_party\", canton_version=~\"$version\"}))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Additional Info: Domain Time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "Domain Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
     "targets": [
      {
       "expr": "splice_sv_status_report_domain_time_us{namespace=~\"$namespace\", report_publisher=~\"$sv_party\", canton_version=~\"$version\"} / 1000",
       "legendFormat": "{{target_node}} - {{ report_publisher }}  {{ report_publisher_party }}"
      }
     ]
    },
    {
     "title": "Domain Time Progress",
     "type": "timeseries",
     "description": "How many seconds of progress on the reported participant domain time is observed every second.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "max by (namespace, report_publisher, target_node) (rate(splice_sv_status_report_domain_time_us{namespace=~\"$namespace\", report_publisher=~\"$sv_party\", canton_version=~\"$version\"}[10m])) / 1000000",
       "legendFormat": "{{target_node}} - {{report_publisher}} @ {{namespace}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Additional Info: Mining rounds",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "panels": [
    {
     "title": "Latest Open Mining Round",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "max by (namespace, report_publisher) (splice_sv_status_report_latest_open_round{namespace=~\"$namespace\", report_publisher=~\"$sv_party\", canton_version=~\"$version\"})",
       "legendFormat": "{{report_publisher}} @ {{namespace}}"
      }
     ]
    },
    {
     "title": "Latest Open Mining Round Lag",
     "type": "timeseries",
     "description": "Should not go above 1 when all SVs are healthy, serves as a basic safeguard to see that the round structure makes progress from all SVs' point of view.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 50 },
     "targets": [
      {
       "expr": "max by (namespace) (max by (report_publisher, namespace) (splice_sv_status_report_latest_open_round{namespace=~\"$namespace\", report_publisher=~\"$sv_party\", canton_version=~\"$version\"}) ) - min by (namespace) (max by (report_publisher, namespace) (splice_sv_status_report_latest_open_round{namespace=~\"$namespace\", report_publisher=~\"$sv_party\", canton_version=~\"$version\"}))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}