{
 "title": "Synchronizer Fees (Validator View)",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(daml_sequencer_client_traffic_control_submitted_event_cost_total,namespace)"
    }
   },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(daml_sequencer_client_traffic_control_submitted_event_cost_total{namespace=\"$namespace\"},job)"
    }
   },
   {
    "name": "synchronizer",
    "label": "Synchronizer",
    "query": {
     "query": "label_values(daml_sequencer_client_traffic_control_submitted_event_cost_total{namespace=\"$namespace\", job=\"$job\"},synchronizer)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Traffic Consumption By Event Type",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Submitted Event Traffic Rate",
   "type": "timeseries",
   "description": "Tracks the traffic cost of events at the time of submission before they've been sequenced.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(type) (rate(daml_sequencer_client_traffic_control_submitted_event_cost_total{namespace=\"$namespace\", job=\"$job\", synchronizer=\"$synchronizer\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Delivered Event Traffic Rate",
   "type": "timeseries",
   "description": "Tracks the actual cost of traffic after events have been sequenced and successfully delivered.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(type) (rate(daml_sequencer_client_traffic_control_event_delivered_cost_total{namespace=\"$namespace\", job=\"$job\", synchronizer=\"$synchronizer\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Event Submission Rate",
   "type": "timeseries",
   "description": "Number of requests that are in-flight, overloaded or dropped per second in the sequencer client.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by(type) (rate(daml_sequencer_client_submissions_in_flight{namespace=\"$namespace\", job=\"$job\", synchronizer=\"$synchronizer\"}[$__rate_interval]))",
     "legendFormat": "in-flight {{type}}"
    },
    {
     "expr": "sum by(type) (rate(daml_sequencer_client_submissions_overloaded{namespace=\"$namespace\", job=\"$job\", synchronizer=\"$synchronizer\"}[$__rate_interval]))",
     "legendFormat": "overloaded {{type}}"
    },
    {
     "expr": "sum by(type) (rate(daml_sequencer_client_submissions_dropped{namespace=\"$namespace\", job=\"$job\", synchronizer=\"$synchronizer\"}[$__rate_interval]))",
     "legendFormat": "dropped {{type}}"
    }
   ]
  },
  {
   "title": "Submitted vs Delivered Traffic",
   "type": "timeseries",
   "description": "Difference in traffic cost for events between submission and successful delivery after sequencing. Small differences can be present due to the time lag between the recorded metrics particularly if there are many requests in-flight to be sequenced.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg_over_time((\n    sum by(type) (daml_sequencer_client_traffic_control_submitted_event_cost_total{namespace=\"$namespace\", job=\"$job\", synchronizer=\"$synchronizer\"})\n    -\n    sum by(type) (daml_sequencer_client_traffic_control_event_delivered_cost_total{namespace=\"$namespace\", job=\"$job\", synchronizer=\"$synchronizer\"})\n)[2m:10s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rejected Event Traffic Rate",
   "type": "timeseries",
   "description": "Shows the traffic cost per second of requests that were sequenced but not delivered successfully by the sequencer. The reason for rejection should be visible in the next graph.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(type) (rate(daml_sequencer_client_traffic_control_event_rejected_cost_total{namespace=\"$namespace\", job=\"$job\", synchronizer=\"$synchronizer\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rejected Event Traffic Rate By Reason",
   "type": "timeseries",
   "description": "Displays the cost per second of events that were sequenced but not delivered successfully aggregated by the reason for the rejection.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(reason) (rate(daml_sequencer_client_traffic_control_event_rejected_cost_total{namespace=\"$namespace\", job=\"$job\", synchronizer=\"$synchronizer\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Traffic Consumption Due to Daml Transactions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 }
  },
  {
   "title": "Confirmation Request Rate By Application ID",
   "type": "timeseries",
   "description": "Shows the traffic consumed due to confirmation requests submitted by this participant (per application ID) along with the consumption due to confirmation responses..",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(application_id) (rate(daml_sequencer_client_traffic_control_event_delivered_cost_total{namespace=\"$namespace\", job=\"$job\", synchronizer=\"$synchronizer\", type=\"send-confirmation-request\"}[$__rate_interval]))",
     "legendFormat": "confirmation-request-rate {{application_id}}"
    },
    {
     "expr": "sum(rate(daml_sequencer_client_traffic_control_event_delivered_cost_total{namespace=\"$namespace\", job=\"$job\", synchronizer=\"$synchronizer\", type=\"send-confirmation-response\"}[$__rate_interval]))",
     "legendFormat": "confirmation-response-rate"
    }
   ]
  },
  {
   "title": "Submitted vs Delivered Traffic By Application ID",
   "type": "timeseries",
   "description": "Difference in traffic cost for confirmation requests and responses between submission and successful delivery after sequencing (per application).",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg_over_time((\n    sum by(application_id) (daml_sequencer_client_traffic_control_submitted_event_cost_total{namespace=\"$namespace\", job=\"$job\", synchronizer=\"$synchronizer\", type=\"send-confirmation-request\"})\n    -\n    sum by(application_id) (daml_sequencer_client_traffic_control_event_delivered_cost_total{namespace=\"$namespace\", job=\"$job\", synchronizer=\"$synchronizer\", type=\"send-confirmation-request\"})\n)[2m:10s])",
     "legendFormat": "confirmation-request {{application_id}}"
    },
    {
     "expr": "avg_over_time((\n    sum without(target_sequencer) (daml_sequencer_client_traffic_control_submitted_event_cost_total{namespace=\"$namespace\", job=\"$job\", synchronizer=\"$synchronizer\", type=\"send-confirmation-response\"})\n    -\n    sum without(member) (daml_sequencer_client_traffic_control_event_delivered_cost_total{namespace=\"$namespace\", job=\"$job\", synchronizer=\"$synchronizer\", type=\"send-confirmation-response\"})\n)[2m:10s])",
     "legendFormat": "confirmation-response"
    }
   ]
  },
  { "title": "Extra Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Extra Traffic Available",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expression": "$extra_traffic_purchased - $extra_traffic_consumed",
     "type": "math"
    }
   ]
  },
  {
   "title": "Extra Traffic Consumed",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(member) (daml_sequencer_client_traffic_control_extra_traffic_consumed{namespace=\"$namespace\", job=\"$job\", synchronizer=\"$synchronizer\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Extra Traffic Purchased over the last 24h",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (member) (delta(daml_sequencer_client_traffic_control_extra_traffic_purchased{namespace=\"$namespace\",job=\"$job\", synchronizer=\"$synchronizer\"}[24h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Extra Traffic Consumed over the last 24h",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (member) (delta(daml_sequencer_client_traffic_control_extra_traffic_consumed{namespace=\"$namespace\",job=\"$job\", synchronizer=\"$synchronizer\"}[24h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Free Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "Free Tier Traffic Available",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(member) (daml_sequencer_client_traffic_control_base_traffic_remainder{namespace=\"$namespace\", job=\"$job\", synchronizer=\"$synchronizer\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}