{
 "title": "Synchronizer Fees (SV View)",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(daml_sequencer_traffic_control_event_delivered_cost_total,namespace)"
    }
   },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(daml_sequencer_traffic_control_event_delivered_cost_total{namespace=\"$namespace\"},job)"
    }
   },
   {
    "name": "member",
    "label": "Member",
    "query": {
     "query": "label_values(daml_sequencer_traffic_control_event_delivered_cost_total{namespace=\"$namespace\", job=\"$job\"},member)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Delivered Event Traffic Rate By Event Type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(type) (rate(daml_sequencer_traffic_control_event_delivered_cost_total{namespace=\"$namespace\", job=\"$job\", member=~\"$member\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rejected Event Traffic Rate By Event Type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(type) (rate(daml_sequencer_traffic_control_event_rejected_cost_total{namespace=\"$namespace\", job=\"$job\", member=~\"$member\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Free Tier Traffic Available By Participant/Mediator",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(member) (daml_sequencer_traffic_control_base_traffic_remainder{namespace=\"$namespace\", job=\"$job\", member=~\"$member\", member=~\"(PAR|MED)::.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Extra Traffic Available By Participant",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expression": "$extra_traffic_purchased - $extra_traffic_consumed",
     "type": "math"
    }
   ]
  },
  {
   "title": "Traffic Purchased over the last 24h",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (member) (delta(daml_sequencer_traffic_control_extra_traffic_purchased{namespace=\"$namespace\",job=\"$job\",member=~\"$member.*\"}[24h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of Wasted Traffic",
   "type": "timeseries",
   "description": "Rate of wasted traffic i.e. sequenced events that cost traffic but are not delivered in bytes/s summed across all participants matching the filter",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (namespace, job, reason) (rate(daml_sequencer_traffic_control_wasted_traffic_total{namespace=~\"$namespace\", member=~\"$member\",member=~\"PAR::.*\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}