{
 "title": "Validator Scan Connections",
 "description": "This dashboard provides validators graphs related to their scan connections.",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(splice_validator_scan_per_connection_latency_duration_seconds,namespace)"
    }
   },
   {
    "name": "job",
    "query": {
     "query": "label_values(splice_validator_scan_per_connection_latency_duration_seconds{namespace=~\"$namespace\"},job)"
    }
   },
   {
    "name": "node_name",
    "query": {
     "query": "label_values(splice_validator_scan_per_connection_latency_duration_seconds{job=~\"$job\", namespace=~\"$namespace\"},node_name)"
    }
   },
   {
    "name": "scan_connection",
    "query": {
     "query": "label_values(splice_validator_scan_per_connection_latency_duration_seconds{namespace=~\"$namespace\", job=~\"$job\", node_name=~\"$node_name\"},scan_connection)"
    }
   },
   { "name": "percentile", "query": "0.99,0.95,0.9" },
   {
    "name": "per_connection_request",
    "query": {
     "query": "label_values(splice_validator_scan_per_connection_latency_duration_seconds{namespace=~\"$namespace\", job=~\"$job\", node_name=~\"$node_name\", scan_connection=~\"$scan_connection\"},request)"
    }
   },
   {
    "name": "bft_request",
    "query": {
     "query": "label_values(splice_validator_scan_bft_read_latency_duration_seconds{namespace=~\"$namespace\", job=~\"$job\", node_name=~\"$node_name\"},request)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Latency per connection",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($percentile, sum by (request, namespace, node_name, scan_connection) (rate(splice_validator_scan_per_connection_latency_duration_seconds{namespace=~\"${namespace}\", job=~\"$job\", node_name=~\"$node_name\", request=~\"${per_connection_request}\", scan_connection=~\"${scan_connection}\"}[$__rate_interval])))",
     "legendFormat": "{{namespace}} - {{node_name}} - {{scan_connection}} - {{request}}"
    }
   ]
  },
  {
   "title": "Errors per connection",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (namespace, node_name, scan_connection, request)(rate(splice_validator_scan_per_connection_calls_total{namespace=~\"$namespace\", job=~\"$job\", node_name=~\"$node_name\", scan_connection=~\"$scan_connection\", request=~\"$per_connection_request\", outcome!=\"ok\"}[$__rate_interval]))",
     "legendFormat": "{{namespace}} - {{node_name}} - {{scan_connection}} - {{request}}"
    }
   ]
  },
  {
   "title": "BFT read latency",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($percentile, sum by (request, namespace, node_name)(rate(splice_validator_scan_bft_read_latency_duration_seconds{namespace=~\"${namespace}\", job=~\"$job\", node_name=~\"$node_name\", request=~\"${bft_request}\"}[$__rate_interval])))",
     "legendFormat": "{{namespace}} - {{node_name}} - {{request}}"
    }
   ]
  },
  {
   "title": "BFT errors",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "sum by (outcome, namespace, node_name, request) (\n  rate(splice_validator_scan_bft_calls_total{namespace=~\"$namespace\", job=~\"$job\", node_name=~\"$node_name\", request=~\"${bft_request}\", outcome!=\"ok\"}[$__rate_interval])\n)",
     "legendFormat": "{{namespace}} - {{node_name}} - {{outcome}} - {{request}}"
    }
   ]
  },
  { "title": "BFT Consensus", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "BFT consensus disagreements per connection",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "sum by (namespace, node_name, scan_connection, consensus, request, http_status) (rate(splice_validator_scan_bft_per_connection_consensus_total{namespace=~\"$namespace\", job=~\"$job\", node_name=~\"$node_name\", scan_connection=~\"$scan_connection\", consensus=\"disagree\", request=~\"${bft_request}\"}[$__rate_interval])) > 0",
     "legendFormat": "{{namespace}} - {{node_name}} - {{scan_connection}} - {{request}} - {{http_status}}"
    }
   ]
  },
  {
   "title": "Disagreements per connection (time range)",
   "type": "table",
   "description": "Total number of times each scan connection disagreed with the BFT consensus result over the selected time range.",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "expr": "sum by (namespace,job, node_name, scan_connection, http_status) (increase(splice_validator_scan_bft_per_connection_consensus_total{consensus=\"disagree\", namespace=~\"$namespace\", job=~\"$job\", node_name=~\"$node_name\", scan_connection=~\"$scan_connection\", request=~\"${bft_request}\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disagreement rate per connection & request ",
   "type": "timeseries",
   "description": "Fraction of BFT consensus comparisons per request on each scan connection that disagreed with the consensus result over the last 30m. Mirrors the warning alert, which fires above 10%.",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum by (namespace, node_name, scan_connection, request) (increase(splice_validator_scan_bft_per_connection_consensus_total{consensus=\"disagree\", namespace=~\"$namespace\", job=~\"$job\", node_name=~\"$node_name\", scan_connection=~\"$scan_connection\", request=~\"${bft_request}\"}[30m]))\n/\nsum by (namespace, node_name, scan_connection, request) (increase(splice_validator_scan_bft_per_connection_consensus_total{namespace=~\"$namespace\", job=~\"$job\", node_name=~\"$node_name\", scan_connection=~\"$scan_connection\", request=~\"${bft_request}\"}[30m]))) > 0",
     "legendFormat": "{{namespace}} - {{node_name}} - {{scan_connection}} - {{request}}"
    }
   ]
  },
  {
   "title": "Successful responses disagreeing with BFT consensus ",
   "type": "timeseries",
   "description": "Number of successful (2xx) responses per request on each scan connection that disagreed with the BFT consensus result over the last 30m. Mirrors the critical alert, which fires above 5.",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (namespace, node_name, scan_connection, request) (increase(splice_validator_scan_bft_per_connection_consensus_total{consensus=\"disagree\", success=\"true\", namespace=~\"$namespace\", job=~\"$job\", node_name=~\"$node_name\", scan_connection=~\"$scan_connection\", request=~\"${bft_request}\"}[30m])) > 0",
     "legendFormat": "{{namespace}} - {{node_name}} - {{scan_connection}} - {{request}}"
    }
   ]
  },
  {
   "title": "Request outcomes per scan connection",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 }
  },
  {
   "title": "$scan_connection",
   "type": "piechart",
   "description": "Total number of requests to this scan connection over the selected time range, split by outcome (ok, or the failure category with its HTTP status code when available).",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 59 },
   "repeat": "scan_connection",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (outcome, http_status) (increase(splice_validator_scan_per_connection_calls_total{namespace=~\"$namespace\", job=~\"$job\", node_name=~\"$node_name\", scan_connection=~\"$scan_connection\", request=~\"${per_connection_request}\"}[$__range]))",
     "legendFormat": "{{outcome}} - {{http_status}}"
    }
   ]
  }
 ]
}