# Configurations here will be applied after app.conf, and before any ADDITIONAL_CONFIG env vars
# Please use this file for temporary changes that require quick iterations. Always add a TO-DO
# issue when adding things here and either alert an upstream team to upstream your changes
# or open PRs to upstream yourself.

# High default, the actual values are expected to be overwritten by SVs based on the configuration in the internal sv repo.
canton.sequencers.sequencer.sequencer.block.throughput-cap.messages.confirmation-response {
  global-tps-cap = 100000
  per-client-tps-cap = 50000
  global-kbps-cap = 100000000
  per-client-kbps-cap = 50000000
}
