{
 "title": "Bulk Storage",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(splice_history_bulk_storage_updates_count,namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Last record time stored",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "targets": [
    {
     "expr": "min by(namespace)((splice_history_bulk_storage_latest_acs_snapshot_staging{namespace=~\"$namespace\"} >-62135596800000) / 1000.0)",
     "legendFormat": "{{namespace}} ACS Snapshots - Staging"
    },
    {
     "expr": "min by(namespace)((splice_history_bulk_storage_latest_updates_segment_staging{namespace=~\"$namespace\"} >-62135596800000) / 1000.0)",
     "legendFormat": "{{namespace}} Updates - Staging"
    },
    {
     "expr": "min by(namespace)((splice_history_bulk_storage_latest_acs_snapshot_committed{namespace=~\"$namespace\"} >-62135596800000) / 1000.0)",
     "legendFormat": "{{namespace}} ACS Snapshots - Committed"
    },
    {
     "expr": "min by(namespace)((splice_history_bulk_storage_latest_updates_segment_committed{namespace=~\"$namespace\"} >-62135596800000) / 1000.0)",
     "legendFormat": "{{namespace}} Updates - Committed"
    }
   ]
  },
  {
   "title": "Catchup rate",
   "type": "timeseries",
   "description": "Rate (compared to wallclock time) at which the latest persisted record time is advancing",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "avg_over_time((deriv(splice_history_bulk_storage_latest_acs_snapshot_staging{namespace=~\"$namespace\"}[$__rate_interval]) / 1000000)[1h:])",
     "legendFormat": "{{namespace}} ACS Snapshots - Staging"
    },
    {
     "expr": "avg_over_time((deriv(splice_history_bulk_storage_latest_updates_segment_staging{namespace=~\"$namespace\"}[$__rate_interval]) / 1000000)[1h:])",
     "legendFormat": "{{namespace}} Updates - Staging"
    },
    {
     "expr": "avg_over_time((deriv(splice_history_bulk_storage_latest_acs_snapshot_committed{namespace=~\"$namespace\"}[$__rate_interval]) / 1000000)[1h:])",
     "legendFormat": "{{namespace}} ACS Snapshots - Committed"
    },
    {
     "expr": "avg_over_time((deriv(splice_history_bulk_storage_latest_updates_segment_committed{namespace=~\"$namespace\"}[$__rate_interval]) / 1000000)[1h:])",
     "legendFormat": "{{namespace}} Updates - Committed"
    }
   ]
  },
  {
   "title": "Processed items",
   "type": "timeseries",
   "description": "Counts items from Scan DB processed into the staging bucket",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "splice_history_bulk_storage_updates_count{namespace=~\"$namespace\"}",
     "legendFormat": "Updates {{namespace}}"
    },
    {
     "expr": "splice_history_bulk_storage_contracts_count{namespace=~\"$namespace\"}",
     "legendFormat": "ACS contracts {{namespace}}"
    }
   ]
  },
  {
   "title": "Rate of processing items",
   "type": "timeseries",
   "description": "Counts items from Scan DB processed into the staging bucket",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(splice_history_bulk_storage_updates_count{namespace=~\"$namespace\"}[$__rate_interval])",
     "legendFormat": "Updates {{namespace}}"
    },
    {
     "expr": "rate(splice_history_bulk_storage_contracts_count{namespace=~\"$namespace\"}[$__rate_interval])",
     "legendFormat": "ACS contracts {{namespace}}"
    }
   ]
  },
  {
   "title": "Num S3 objects stored",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "splice_history_bulk_storage_object_count{namespace=~\"$namespace\"}",
     "legendFormat": "{{namespace}} {{object_type}} {{encoding}} - {{bucket}}"
    }
   ]
  },
  {
   "title": "S3 objects storage rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "avg_over_time(rate(splice_history_bulk_storage_object_count{namespace=~\"$namespace\"}[$__rate_interval])[1h:])",
     "legendFormat": "{{namespace}} {{object_type}} {{encoding}} - {{bucket}}"
    }
   ]
  }
 ]
}