{
 "title": "Splice Stores Ingestion",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(splice_store_last_ingested_record_time_ms,namespace)"
    }
   },
   {
    "name": "node_name",
    "query": {
     "query": "label_values(splice_store_last_ingested_record_time_ms,node_name)"
    }
   },
   {
    "name": "store_name",
    "query": {
     "query": "label_values(splice_store_last_ingested_record_time_ms,store_name)"
    }
   },
   {
    "name": "store_party",
    "query": {
     "query": "label_values(splice_store_last_ingested_record_time_ms,store_party)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Ingestion timing",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, namespace,job,store_name,store_party,synchronizer_id) (rate(splice_store_batch_ingestion_latency_duration_seconds{namespace=~\"$namespace\", node_name=~\"$node_name\", store_name=~\"$store_name\", store_party=~\"$store_party\"}[$__rate_interval])))",
     "legendFormat": "95% - {{namespace}} {{job}} {{store_name}} {{store_party}} {{synchronizer_id}}"
    },
    {
     "expr": "histogram_avg(rate(splice_store_batch_ingestion_latency_duration_seconds{namespace=~\"$namespace\", node_name=~\"$node_name\", store_name=~\"$store_name\", store_party=~\"$store_party\"}[$__rate_interval]))",
     "legendFormat": "avg - {{namespace}} {{job}} {{store_name}} {{store_party}} {{synchronizer_id}}"
    }
   ]
  },
  {
   "title": "Ingestion rate",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_count(rate(splice_store_batch_ingestion_latency_duration_seconds{namespace=~\"$namespace\",node_name=~\"$node_name\",store_name=~\"$store_name\",store_party=~\"$store_party\"}[$__rate_interval]))",
     "legendFormat": "{{namespace}} {{job}} {{store_name}} {{store_party}} {{synchronizer_id}}"
    }
   ]
  },
  {
   "title": "Batch size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le, namespace,job,store_name,store_party,synchronizer_id) (rate(splice_store_ingestion_batch_size{namespace=~\"$namespace\", node_name=~\"$node_name\", store_name=~\"$store_name\", store_party=~\"$store_party\"}[$__rate_interval])))",
     "legendFormat": "99% - {{namespace}} {{job}} {{store_name}} {{store_party}} {{synchronizer_id}}"
    },
    {
     "expr": "histogram_avg(sum by (le, namespace,job,store_name,store_party,synchronizer_id) (rate(splice_store_ingestion_batch_size{namespace=~\"$namespace\", node_name=~\"$node_name\", store_name=~\"$store_name\", store_party=~\"$store_party\"}[$__rate_interval])))",
     "legendFormat": "avg - {{namespace}} {{job}} {{store_name}} {{store_party}} {{synchronizer_id}}"
    }
   ]
  },
  {
   "title": "Events",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Ingestion rate events",
     "type": "timeseries",
     "description": "How many events (created / archived) were ingested per $rate_interval",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 77 },
     "targets": [
      {
       "expr": "rate(splice_store_event_count{namespace=~\"$namespace\", node_name=~\"$node_name\", store_name=~\"$store_name\", store_party=~\"$store_party\", event_type=\"archived\"}[$__rate_interval])",
       "legendFormat": "__auto"
      },
      {
       "expr": "rate(splice_store_event_count{namespace=~\"$namespace\", node_name=~\"$node_name\", store_name=~\"$store_name\", store_party=~\"$store_party\", event_type=\"created\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Record time metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Last Ingested Record Time Lag",
     "type": "timeseries",
     "description": "The time difference between the last ingested record time and the current wallclock time.\n\nNote that the last ingested record time metric only updates when the store ingests a new transaction so if there is no activity, the last ingested record time will not advance. For a party performing reward collection, e.g., the validator operator party you expect at least one transaction every round so the lag should not go above 20min.",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "(timestamp(splice_store_last_ingested_record_time_ms{namespace=~\"$namespace\",node_name=~\"$node_name\",store_name=~\"$store_name\",store_party=~\"$store_party\"}) - (splice_store_last_ingested_record_time_ms{namespace=~\"$namespace\",node_name=~\"$node_name\",store_name=~\"$store_name\",store_party=~\"$store_party\"} > 0) / 1e3)",
       "legendFormat": "{{namespace}} {{job}} {{store_name}} {{store_party}} {{synchronizer_id}}"
      }
     ]
    },
    {
     "title": "Last Ingested Record Time",
     "type": "timeseries",
     "description": "The last ingested record time for each store.\n\nNote that the last ingested record time metric only updates when the store ingests a new transaction so if no transaction is ingested the last ingested time will not advance. For a party performing reward collection, e.g., the validator operator party you expect at least one transaction every round so the last ingested time should be at most 20min ago.",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
     "targets": [
      {
       "expr": "splice_store_last_ingested_record_time_ms{namespace=~\"$namespace\",node_name=~\"$node_name\",store_name=~\"$store_name\",store_party=~\"$store_party\"}",
       "legendFormat": "{{namespace}} {{job}} {{store_name}} {{store_party}} {{synchronizer_id}}"
      }
     ]
    },
    {
     "title": "Last Seen Record Time Lag",
     "type": "timeseries",
     "description": "The time difference between the last seen record time and the current wallclock time.\n\nThe last seen record time updates regardless of whether an update was ingested or filtered out.",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "(timestamp(splice_store_last_seen_record_time_ms{namespace=~\"$namespace\",node_name=~\"$node_name\",store_name=~\"$store_name\",store_party=~\"$store_party\"}) - (splice_store_last_seen_record_time_ms{namespace=~\"$namespace\",node_name=~\"$node_name\",store_name=~\"$store_name\",store_party=~\"$store_party\"} > 0) / 1e3)",
       "legendFormat": "{{namespace}} {{job}} {{store_name}} {{store_party}} {{synchronizer_id}}"
      }
     ]
    },
    {
     "title": "Last Seen Record Time",
     "type": "timeseries",
     "description": "The most recent record time seen by this store for each synchronizer in milliseconds.\n\nThis updates for every entry seen, regardless of whether it was ingested or filtered out.",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
     "targets": [
      {
       "expr": "splice_store_last_seen_record_time_ms{namespace=~\"$namespace\",node_name=~\"$node_name\",store_name=~\"$store_name\",store_party=~\"$store_party\"}",
       "legendFormat": "{{namespace}} {{job}} {{store_name}} {{store_party}} {{synchronizer_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "TxLog",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Ingestion rate txlog entries",
     "type": "timeseries",
     "description": "How many txlog entries were ingested per $rate_interval",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 102 },
     "targets": [
      {
       "expr": "rate(splice_store_ingested_tx_log_entries_total{namespace=~\"$namespace\", node_name=~\"$node_name\", store_name=~\"$store_name\", store_party=~\"$store_party\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}