alter table acs_snapshot
  -- the name 'table_name' is not reserved, but it is a PostgreSQL keyword, so we use a different name to avoid confusion
  add column data_table_name text default null,
  -- these values won't be set anymore
  drop constraint acs_snapshot_first_row_id_fkey,
  drop constraint acs_snapshot_last_row_id_fkey,
  alter column first_row_id drop not null,
  alter column last_row_id drop not null,
  -- ensure consistency
  add constraint legacy_or_per_snapshot check
    -- per-snapshot tables
    ((first_row_id is null and last_row_id is null and data_table_name is not null) or
    -- legacy table
    (first_row_id is not null and last_row_id is not null and data_table_name is null));

-- Same as acs_incremental_snapshot, except it doesn't include a table name, as that's implied from the target_record_time,
-- and this is not meant for backfilling.
create table acs_snapshot_progress
(
    snapshot_id                     bigint generated by default as identity primary key,
    history_id                      bigint not null references update_history_descriptors (id),

    -- The time as of which this snapshot represents the ACS.
    -- Alternatively: progress done, up until target_record_time.
    record_time                     bigint not null,
    migration_id                    bigint not null,

    -- The time at which the snapshot is finished.
    target_record_time              bigint not null,
    check (record_time <= target_record_time) -- when equal, the snapshot is finished
);

create unique index acs_snapshot_progress_hi_trt on acs_snapshot_progress (history_id, target_record_time desc);
