alter table acs_snapshot
  -- the name 'table_name' is not reserved, but it is a PostgreSQL keyword, so we use a different name to avoid confusion
  add column data_table_name text default null,
  -- these values won't be set anymore
  drop constraint acs_snapshot_first_row_id_fkey,
  drop constraint acs_snapshot_last_row_id_fkey,
  alter column first_row_id drop not null,
  alter column last_row_id drop not null,
  -- ensure consistency
  add constraint legacy_or_per_snapshot check
    -- per-snapshot tables
    ((first_row_id is null and last_row_id is null and data_table_name is not null) or
    -- legacy table
    (first_row_id is not null and last_row_id is not null and data_table_name is null));

-- Same as acs_incremental_snapshot_data_next, but includes the create_arguments.
create table acs_incremental_snapshot_data_nextv2
(
    -- In production, we have a separate table for each scan instance so this
    -- column will be the same for all rows. However, in tests we can have multiple
    -- scan instances writing to the same table, so we need to include it.
    snapshot_id             bigint  not null references acs_incremental_snapshot (snapshot_id),

    contract_id             text    not null,

    -- Contract data included to avoid joining with UpdateHistory tables
    -- during the expensive operation of saving incremental ACS snapshots.
    create_arguments        jsonb   not null,
    created_at              bigint  not null,
    unlocked_amulet_balance numeric not null, -- zero for non-amulet contracts
    locked_amulet_balance   numeric not null, -- zero for non-amulet contracts
    template_id             text    not null,
    stakeholders            text[]  not null
);

-- Template table for acs_snapshot_creates_<record_time_epoch>.
-- This allows the code to just CREATE TABLE LIKE acs_snapshot_creates_template or acs_snapshot_stakeholders_template.
-- Design decision: we don't have a single table per (contract_id, stakeholder) in order to avoid duplicating the create_arguments.
create table acs_snapshot_creates_template
(
    contract_id       text   primary key,
    create_arguments  jsonb  not null,
    -- We might be able to derive signatories and observers from stakeholders, but this is easier
    signatories       text[] not null,
    observers         text[] not null,
    -- plus the Amulet-specific balance columns currently computed in the working table
    unlocked_amulet_balance numeric,
    locked_amulet_balance   numeric
);

create table acs_snapshot_stakeholders_template
(
    -- Important: insertion order should happen by (created_at, contract_id) for:
    -- 1) backwards compatibility
    -- 2) deterministic ordering across SVs
    row_id      bigint generated by default as identity primary key,
    stakeholder text not null,
    template_id text not null,
    contract_id text not null
);

-- Necessary indexes:
-- 1) (stakeholder, template_id, row_id) for where stakeholder=? and template_id=? order by row_id
-- 2) (stakeholder, row_id) for where stakeholder=? order by row_id
-- In both cases `include (contract_id)` allows index-only scans to then merge with acs_snapshot_creates_template
