{
 "title": "Executor",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(daml_db_commit_duration_seconds,namespace)"
    }
   },
   {
    "name": "job",
    "query": {
     "query": "label_values(db_client_connections_usage{namespace=~\"$namespace\"},job)"
    }
   },
   { "name": "libs", "query": "cn,daml" },
   { "name": "db_pool", "query": "general,write,locks" },
   {
    "name": "query",
    "query": {
     "query": "label_values({job=~\"$job\", namespace=~\"$namespace\"},query)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Daml",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "panels": [
    {
     "title": "Query Time",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
     "repeat": "db_pool",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(namespace, node_name, node_type, component, name, node) (rate(daml_db_query_duration_seconds{namespace=~\"$namespace\", job=~\"$job\"}[$__rate_interval]))) > 0",
       "legendFormat": "0.95 {{namespace}} {{node_name}} {{node}} {{name}}"
      }
     ]
    },
    {
     "title": "Wait Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
     "repeat": "db_pool",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(namespace, node_name, node_type, component, name, node) (rate(daml_db_wait_duration_seconds{namespace=~\"$namespace\", job=~\"$job\"}[$__rate_interval]))) > 0",
       "legendFormat": "0.95 {{namespace}} {{node_name}} {{node}} {{name}}"
      }
     ]
    },
    {
     "title": "Exec Time",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
     "repeat": "db_pool",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(namespace, node_name, node_type, component, name, node) (rate(daml_db_exec_duration_seconds{namespace=~\"$namespace\", job=~\"$job\"}[$__rate_interval]))) > 0",
       "legendFormat": "0.95 {{namespace}} {{node_name}} {{node}} {{name}}"
      }
     ]
    },
    {
     "title": "Commit Time",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
     "repeat": "db_pool",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(namespace, node_name, node_type, component, name, node) (rate(daml_db_commit_duration_seconds{namespace=~\"$namespace\", job=~\"$job\"}[$__rate_interval]))) > 0",
       "legendFormat": "0.95 {{namespace}} {{node_name}} {{node}} {{name}}"
      }
     ]
    }
   ]
  },
  { "title": "Db $libs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 }, "repeat": "libs" },
  {
   "title": "Waittime ${db_pool}",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 26 },
   "repeat": "db_pool",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(namespace, node_name, node_type, component, name, node, query) (rate(${libs}_db_storage_${db_pool}_executor_waittime_duration_seconds{namespace=~\"$namespace\", job=~\"$job\", query=~\"$query\"}[$__rate_interval])))",
     "legendFormat": "0.99 {{namespace}} {{node_name}} {{node}} {{query}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(namespace, node_name, node_type, component, name, node, query) (rate(${libs}_db_storage_${db_pool}_executor_waittime_duration_seconds{namespace=~\"$namespace\", job=~\"$job\", query=~\"$query\"}[$__rate_interval])))",
     "legendFormat": "0.95 {{namespace}} {{node_name}}{{node}} {{query}}"
    },
    {
     "expr": "sum by(namespace, node_name, node_type, component, name, node, query) (histogram_avg(rate(${libs}_db_storage_${db_pool}_executor_waittime_duration_seconds{namespace=~\"$namespace\", job=~\"$job\", query=~\"$query\"}[$__rate_interval])))",
     "legendFormat": "avg {{namespace}} {{node_name}}{{node}} {{query}}"
    }
   ]
  },
  {
   "title": "Query count ${db_pool}",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 17 },
   "repeat": "db_pool",
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by(namespace, node_name, node_type, component, name, node, query) (\n  histogram_count(\n    rate(${libs}_db_storage_${db_pool}_executor_exectime_duration_seconds{namespace=~\"$namespace\", job=~\"$job\", query=~\"$query\"}[$__rate_interval])\n  )\n)",
     "legendFormat": "{{namespace}} {{node_name}} {{node}} {{query}}"
    }
   ]
  },
  {
   "title": "Exectime ${db_pool}",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 41 },
   "repeat": "db_pool",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(namespace, node_name, node_type, component, name, node, query) (rate(${libs}_db_storage_${db_pool}_executor_exectime_duration_seconds{namespace=~\"$namespace\", job=~\"$job\", query=~\"$query\"}[$__rate_interval])))",
     "legendFormat": "0.95 {{namespace}} {{node_name}} {{node}} {{query}}"
    }
   ]
  },
  {
   "title": "Running executor ${db_pool}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 56 },
   "repeat": "db_pool",
   "targets": [
    {
     "expr": "${libs}_db_storage_${db_pool}_executor_running{namespace=~\"$namespace\", job=~\"$job\", query=~\"$query\"}",
     "legendFormat": "{{namespace}} {{node_name}}{{node}} {{query}}"
    }
   ]
  },
  {
   "title": "Queued executor ${db_pool}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 66 },
   "repeat": "db_pool",
   "targets": [
    {
     "expr": "${libs}_db_storage_${db_pool}_executor_queued{namespace=~\"$namespace\", job=~\"$job\", query=~\"$query\"}",
     "legendFormat": "{{namespace}} {{node_name}} {{node}} {{query}}"
    }
   ]
  }
 ]
}