{
 "title": "PostgreSQL Database",
 "description": "This dashboard works with postgres_exporter for prometheus",
 "tags": [
  "postgres",
  "db",
  "stats"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "query_result(pg_exporter_last_scrape_duration_seconds)"
   },
   {
    "name": "service",
    "label": "Exporter",
    "query": {
     "query": "label_values(pg_up{namespace=\"$namespace\"},service)"
    }
   },
   {
    "name": "datname",
    "label": "Database",
    "query": {
     "query": "label_values(pg_database_size_bytes{namespace=\"$namespace\", instance=~\"$instance\", service=~\"$service\"},datname)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(pg_up{namespace=\"$namespace\", service=~\"$service\"},instance)"
    }
   },
   {
    "name": "mode",
    "label": "Lock table",
    "query": "label_values({mode=~\"accessexclusivelock|accesssharelock|exclusivelock|rowexclusivelock|rowsharelock|sharelock|sharerowexclusivelock|shareupdateexclusivelock\"}, mode)"
   },
   {
    "name": "server",
    "label": "Server",
    "query": {
     "query": "label_values(pg_stat_user_tables_table_size_bytes{namespace=\"$namespace\", datname=~\"$datname\"},server)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "General Counters, CPU, Memory and File Descriptor Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pg_static{server=\"$server\", namespace=\"$namespace\", instance=~\"$instance\", service=~\"$service\"}",
     "legendFormat": "{{short_version}}"
    }
   ]
  },
  {
   "title": "Current fetch data",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "rowsps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(pg_stat_database_tup_fetched{server=\"$server\", namespace=~\"$namespace\", datname=~\"$datname\", instance=~\"$instance\", service=~\"$service\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Current insert data",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "rowsps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(pg_stat_database_tup_inserted{server=\"$server\", namespace=~\"$namespace\", datname=~\"$datname\", instance=~\"$instance\", service=~\"$service\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Current update data",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "rowsps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(pg_stat_database_tup_updated{server=\"$server\", namespace=~\"$namespace\", datname=~\"$datname\", instance=~\"$instance\", service=~\"$service\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Max Connections",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pg_settings_max_connections{server=\"$server\", namespace=\"$namespace\", instance=~\"$instance\", service=~\"$service\"}"
    }
   ]
  },
  {
   "title": "Average CPU Usage",
   "type": "timeseries",
   "description": "Average user and system CPU time spent in seconds.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(rate(process_cpu_seconds_total{server=\"$server\", namespace=\"$namespace\", instance=~\"$instance\", service=~\"$service\"}[5m]) * 1000)",
     "legendFormat": "CPU Time"
    }
   ]
  },
  {
   "title": "Average Memory Usage",
   "type": "timeseries",
   "description": "Virtual and Resident memory size in bytes, averages over 5 min interval",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(rate(process_resident_memory_bytes{namespace=\"$namespace\", instance=~\"$instance\", service=~\"$service\"}[5m]))",
     "legendFormat": "Resident Mem"
    },
    {
     "expr": "avg(rate(process_virtual_memory_bytes{server=\"$server\", namespace=\"$namespace\", instance=~\"$instance\", service=~\"$service\"}[5m]))",
     "legendFormat": "Virtual Mem"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "timeseries",
   "description": "Number of open file descriptors",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "process_open_fds{server=\"$server\", namespace=\"$namespace\", instance=~\"$instance\", service=~\"$service\"}",
     "legendFormat": "Open FD"
    }
   ]
  },
  { "title": "Database Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Active sessions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "pg_stat_activity_count{namespace=~\"$namespace\", datname=~\"$datname\", instance=~\"$instance\", state=\"active\"} !=0",
     "legendFormat": "{{datname}} - {{usename}} - {{application_name}}"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(pg_stat_database_xact_commit{namespace=\"$namespace\", instance=~\"$instance\", datname=~\"$datname\"}[$__rate_interval])",
     "legendFormat": "{{datname}} commits"
    },
    {
     "expr": "irate(pg_stat_database_xact_rollback{namespace=\"$namespace\", instance=~\"$instance\", datname=~\"$datname\"}[$__rate_interval])",
     "legendFormat": "{{datname}} rollbacks"
    }
   ]
  },
  {
   "title": "Update data",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "rowsps" } },
   "targets": [
    {
     "expr": "sum by(instance, datname, namespace) (rate(pg_stat_database_tup_updated{namespace=~\"$namespace\", datname=~\"$datname\", instance=~\"$instance\", service=~\"$service\"}[$__rate_interval]) != 0)",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Fetch data (SELECT)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "rowsps" } },
   "targets": [
    {
     "expr": "sum by(instance, datname, namespace) (rate(pg_stat_database_tup_fetched{namespace=~\"$namespace\", datname=~\"$datname\", instance=~\"$instance\", service=~\"$service\"}[$__rate_interval]) != 0)",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Idle sessions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pg_stat_activity_count{namespace=~\"$namespace\", datname=~\"$datname\", instance=~\"$instance\", state=~\"idle|idle in transaction|idle in transaction (aborted)\"}",
     "legendFormat": "{{datname}} {{usename}}, s: {{state}}"
    }
   ]
  },
  {
   "title": "Return data",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "rowsps" } },
   "targets": [
    {
     "expr": "sum by(instance, datname, namespace) (rate(pg_stat_database_tup_returned{namespace=~\"$namespace\", datname=~\"$datname\", instance=~\"$instance\", service=~\"$service\"}[$__rate_interval]) != 0)",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Cache Hit Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "pg_stat_database_blks_hit{namespace=\"$namespace\", instance=~\"$instance\", datname=~\"$datname\"} / (pg_stat_database_blks_read{namespace=\"$namespace\", instance=~\"$instance\", datname=~\"$datname\"} + pg_stat_database_blks_hit{namespace=\"$namespace\", instance=~\"$instance\", datname=~\"$datname\"})",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "Buffers (bgwriter)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(pg_stat_bgwriter_buffers_backend_total{namespace=\"$namespace\", instance=~\"$instance\", service=~\"$service\"}[$__rate_interval])",
     "legendFormat": "buffers_backend"
    },
    {
     "expr": "irate(pg_stat_bgwriter_buffers_alloc_total{namespace=\"$namespace\", instance=~\"$instance\", service=~\"$service\"}[$__rate_interval])",
     "legendFormat": "buffers_alloc"
    },
    {
     "expr": "irate(pg_stat_bgwriter_buffers_backend_fsync_total{namespace=\"$namespace\", instance=~\"$instance\", service=~\"$service\"}[$__rate_interval])",
     "legendFormat": "backend_fsync"
    },
    {
     "expr": "irate(pg_stat_bgwriter_buffers_checkpoint_total{namespace=\"$namespace\", instance=~\"$instance\", service=~\"$service\"}[$__rate_interval])",
     "legendFormat": "buffers_checkpoint"
    },
    {
     "expr": "irate(pg_stat_bgwriter_buffers_clean_total{namespace=\"$namespace\", instance=~\"$instance\", service=~\"$service\"}[$__rate_interval])",
     "legendFormat": "buffers_clean"
    }
   ]
  },
  {
   "title": "Delete data",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "rowsps" } },
   "targets": [
    {
     "expr": "sum by(instance, datname, namespace) (rate(pg_stat_database_tup_deleted{namespace=~\"$namespace\", datname=~\"$datname\", instance=~\"$instance\", service=~\"$service\"}[$__rate_interval]) != 0)",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Temp File (Bytes)",
   "type": "timeseries",
   "description": "Total amount of data written to temporary files by queries in this database. All temporary files are counted, regardless of why the temporary file was created, and regardless of the log_temp_files setting.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "irate(pg_stat_database_temp_bytes{namespace=\"$namespace\", instance=~\"$instance\", datname=~\"$datname\"}[$__rate_interval])",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Insert data",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "rowsps" } },
   "targets": [
    {
     "expr": "sum by(instance, datname, namespace) (rate(pg_stat_database_tup_inserted{namespace=~\"$namespace\", datname=~\"$datname\", instance=~\"$instance\", service=~\"$service\"}[$__rate_interval]) != 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lock tables",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pg_locks_count{namespace=~\"$namespace\", datname=~\"$datname\", instance=~\"$instance\", mode=~\"$mode\"} != 0",
     "legendFormat": "{{datname}},{{mode}}"
    }
   ]
  },
  {
   "title": "Conflicts/Deadlocks",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(pg_stat_database_conflicts{namespace=\"$namespace\", instance=~\"$instance\", datname=~\"$datname\"}[5m])",
     "legendFormat": "{{datname}} conflicts"
    },
    {
     "expr": "irate(pg_stat_database_deadlocks{namespace=\"$namespace\", instance=~\"$instance\", datname=~\"$datname\"}[5m])",
     "legendFormat": "{{datname}} deadlocks"
    }
   ]
  },
  {
   "title": "Checkpoint Stats",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "irate(pg_stat_bgwriter_checkpoint_write_time_total{namespace=\"$namespace\", instance=~\"$instance\", service=~\"$service\"}[$__rate_interval])",
     "legendFormat": "write_time - Total amount of time that has been spent in the portion of checkpoint processing where files are written to disk."
    },
    {
     "expr": "irate(pg_stat_bgwriter_checkpoint_sync_time_total{namespace=\"$namespace\", instance=~\"$instance\", service=~\"$service\"}[$__rate_interval])",
     "legendFormat": "sync_time - Total amount of time that has been spent in the portion of checkpoint processing where files are synchronized to disk."
    }
   ]
  },
  { "title": "User tables", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Fetch data table (SELECT)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "rowsps" } },
   "targets": [
    {
     "expr": "sum by(instance, datname, namespace, relname, schemaname) (rate(pg_stat_user_tables_seq_tup_read{namespace=~\"$namespace\", datname=~\"$datname\", instance=~\"$instance\", service=~\"$service\"}[$__rate_interval]) != 0)",
     "legendFormat": "Seq scan - {{relname}}"
    },
    {
     "expr": "sum by(instance, datname, namespace, relname, schemaname) (rate(pg_stat_user_tables_idx_tup_fetch{namespace=~\"$namespace\", datname=~\"$datname\", instance=~\"$instance\", service=~\"$service\"}[$__rate_interval]) != 0)",
     "legendFormat": "Index scan - {{relname}}"
    }
   ]
  },
  {
   "title": "Scans",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 16, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by(instance, datname, namespace, relname, schemaname) (rate(pg_stat_user_tables_seq_scan{namespace=~\"$namespace\", datname=~\"$datname\", instance=~\"$instance\", service=~\"$service\"}[$__rate_interval]) != 0)",
     "legendFormat": "Seq {{relname}}"
    },
    {
     "expr": "sum by(instance, datname, namespace, relname, schemaname) (rate(pg_stat_user_tables_idx_scan{namespace=~\"$namespace\", datname=~\"$datname\", instance=~\"$instance\", service=~\"$service\"}[$__rate_interval]) != 0)",
     "legendFormat": "Idx  {{relname}}"
    }
   ]
  },
  {
   "title": "Live Rows",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "Rows" } },
   "targets": [
    {
     "expr": "pg_stat_user_tables_n_live_tup{namespace=~\"$namespace\", datname=~\"$datname\", instance=~\"$instance\", service=~\"$service\"} > 0",
     "legendFormat": "{{relname}}"
    }
   ]
  },
  {
   "title": "Updates",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "rowsps" } },
   "targets": [
    {
     "expr": "sum by(instance, datname, namespace, relname, schemaname) (rate(pg_stat_user_tables_n_tup_upd{namespace=~\"$namespace\", datname=~\"$datname\", instance=~\"$instance\", service=~\"$service\"}[$__rate_interval]) != 0)",
     "legendFormat": "Update - {{relname}}"
    },
    {
     "expr": "sum by(instance, datname, namespace, relname, schemaname) (rate(pg_stat_user_tables_n_tup_hot_upd{namespace=~\"$namespace\", datname=~\"$datname\", instance=~\"$instance\", service=~\"$service\"}[$__rate_interval]) != 0)",
     "legendFormat": "Hot Update - {{relname}}"
    }
   ]
  },
  {
   "title": "Inserts",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 7, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "rowsps" } },
   "targets": [
    {
     "expr": "sum by(instance, datname, namespace, relname, schemaname) (rate(pg_stat_user_tables_n_tup_ins{namespace=~\"$namespace\", datname=~\"$datname\", instance=~\"$instance\", service=~\"$service\"}[$__rate_interval]) != 0)",
     "legendFormat": "{{relname}}"
    }
   ]
  },
  {
   "title": "Deletes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "rowsps" } },
   "targets": [
    {
     "expr": "sum by(instance, datname, namespace, relname, schemaname) (rate(pg_stat_user_tables_n_tup_del{namespace=~\"$namespace\", datname=~\"$datname\", instance=~\"$instance\", service=~\"$service\"}[$__rate_interval]) != 0)",
     "legendFormat": "{{relname}}"
    }
   ]
  },
  {
   "title": "Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "pg_stat_user_tables_table_size_bytes{namespace=~\"$namespace\", datname=~\"$datname\", instance=~\"$instance\", service=~\"$service\"} > 0",
     "legendFormat": "{{relname}}"
    }
   ]
  },
  { "title": "Analyze & Vacuum", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 87 } },
  {
   "title": "Last Autoanalyze",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "targets": [
    {
     "expr": "pg_stat_user_tables_last_autoanalyze{namespace=~\"$namespace\", datname=~\"$datname\", instance=~\"$instance\", service=~\"$service\"} * 1000 > 0",
     "legendFormat": "{{datname}} {{relname}}"
    }
   ]
  },
  {
   "title": "Rows Since Last Autoanalyze",
   "type": "timeseries",
   "description": "Number of rows changed since last auto analyze",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "rows" } },
   "targets": [
    {
     "expr": "pg_stat_user_tables_n_mod_since_analyze{namespace=~\"$namespace\", datname=~\"$datname\", instance=~\"$instance\", service=~\"$service\"}",
     "legendFormat": "{{datname}} {{relname}}"
    }
   ]
  },
  {
   "title": "Last Autovacuum",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "targets": [
    {
     "expr": "pg_stat_user_tables_last_autovacuum{namespace=~\"$namespace\", datname=~\"$datname\", instance=~\"$instance\", service=~\"$service\"} * 1000 > 0",
     "legendFormat": "{{datname}} {{relname}}"
    }
   ]
  },
  {
   "title": "Dead Tuples",
   "type": "timeseries",
   "description": "Number of dead tuples per table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "rows" } },
   "targets": [
    {
     "expr": "pg_stat_user_tables_n_dead_tup{namespace=~\"$namespace\", datname=~\"$datname\", instance=~\"$instance\", service=~\"$service\"}",
     "legendFormat": "{{datname}} {{relname}}"
    }
   ]
  },
  { "title": "Settings", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 104 } },
  {
   "title": "Shared Buffers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_shared_buffers_bytes{server=\"$server\", namespace=\"$namespace\", instance=~\"$instance\", service=~\"$service\"}"
    }
   ]
  },
  {
   "title": "Effective Cache",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_effective_cache_size_bytes{server=\"$server\", namespace=\"$namespace\", instance=~\"$instance\", service=~\"$service\"}"
    }
   ]
  },
  {
   "title": "Maintenance Work Mem",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_maintenance_work_mem_bytes{server=\"$server\", namespace=\"$namespace\", instance=~\"$instance\", service=~\"$service\"}"
    }
   ]
  },
  {
   "title": "Work Mem",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_work_mem_bytes{server=\"$server\", namespace=\"$namespace\", instance=~\"$instance\", service=~\"$service\"}"
    }
   ]
  },
  {
   "title": "Max WAL Size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_max_wal_size_bytes{server=\"$server\", namespace=\"$namespace\", instance=~\"$instance\", service=~\"$service\"}"
    }
   ]
  },
  {
   "title": "Random Page Cost",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_random_page_cost{server=\"$server\", namespace=\"$namespace\", instance=~\"$instance\", service=~\"$service\"}"
    }
   ]
  },
  {
   "title": "Seq Page Cost",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_seq_page_cost{server=\"$server\", namespace=\"$namespace\", instance=~\"$instance\", service=~\"$service\"}"
    }
   ]
  },
  {
   "title": "Max Worker Processes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pg_settings_max_worker_processes{server=\"$server\", namespace=\"$namespace\", instance=~\"$instance\", service=~\"$service\"}"
    }
   ]
  },
  {
   "title": "Max Parallel Workers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_max_parallel_workers{server=\"$server\", namespace=\"$namespace\", instance=~\"$instance\", service=~\"$service\"}"
    }
   ]
  }
 ]
}