name: Deploy CIMain
on:
  push:
    branches:
      - 'main'

permissions:
  id-token: write

jobs:
  trigger_cimain:
    uses: ./.github/workflows/cluster_tests.yml
    secrets: inherit
    with:
      workflow: deploy_cimain
      sha: ${{ github.sha }}
