name: Cleanup Nix Cache

on:
  schedule:
    - cron: '0 4 * * *'  # daily at 04:00 UTC
  workflow_dispatch:
    inputs:
      max_age_days:
        description: "Delete cache entries older than this many days"
        type: string
        required: false
        default: "30"

jobs:
  cleanup:
    runs-on: self-hosted-k8s-small
    container:
      image: us-central1-docker.pkg.dev/da-cn-shared/ghcr/digital-asset/decentralized-canton-sync-dev/docker/splice-test-ci:0.3.12
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          submodules: recursive
      - uses: ./.github/actions/nix/cleanup_nix_cache
        with:
          max_age_days: ${{ inputs.max_age_days || '30' }}
          workload_identity_provider: ${{ secrets.GOOGLE_WORKLOAD_IDENTITY_PROVIDER }}
          failure_notifications_sa: ${{ secrets.FAILURE_NOTIFICATIONS_INVOKER_SA }}
          failure_notifications_url: ${{ secrets.FAILURE_NOTIFICATIONS_INVOKER_URL }}
          failure_notifications_slack_channel: ${{ secrets.FAILURE_NOTIFICATIONS_SLACK_CHANNEL }}
