name: TEST
on:
  pull_request:

jobs:
  test:
    name: TEST
    runs-on: self-hosted-k8s-small
    container:
      image: us-central1-docker.pkg.dev/da-cn-shared/ghcr/digital-asset/decentralized-canton-sync-dev/docker/splice-test-ci:0.3.12
    permissions:
      id-token: write # Required for GCP Workload Identity for failure notifications
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: recursive
          token: '${{ secrets.GH_CREATE_PRS_TOKEN }}' # need to checkout with a stronger token to be able to push later 

      - name: Report Failures on Slack & Github
        if: always()
        uses: ./splice-shared-gha/.github/actions/tests/failure_notifications
        with:
          workload_identity_provider: '${{ secrets.GOOGLE_WORKLOAD_IDENTITY_PROVIDER }}'
          service_account: '${{ secrets.FAILURE_NOTIFICATIONS_INVOKER_SA }}'
          notifications_url: '${{ secrets.FAILURE_NOTIFICATIONS_INVOKER_URL }}'
          slack_channel: '${{ secrets.FAILURE_NOTIFICATIONS_SLACK_CHANNEL }}'
